/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Round-trips the Better Auth JWT through FastAPI's JWKS validation — id/role
         *     come straight from the validated claims, no DB read yet (User Profile module owns
         *     the domain profile; this just proves the auth pipeline works end to end).
         */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_v1_users_me_profile_get"];
        /** Update My Profile */
        put: operations["update_my_profile_api_v1_users_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skin Types */
        get: operations["get_skin_types_api_v1_skin_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin-concerns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skin Concerns */
        get: operations["get_skin_concerns_api_v1_skin_concerns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin-profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Skin Profile */
        get: operations["get_my_skin_profile_api_v1_skin_profiles_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create My Skin Profile */
        post: operations["create_my_skin_profile_api_v1_skin_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lifestyle-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert My Lifestyle Log */
        post: operations["upsert_my_lifestyle_log_api_v1_lifestyle_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lifestyle-logs/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Lifestyle Logs */
        get: operations["get_my_lifestyle_logs_api_v1_lifestyle_logs_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EnvironmentalExposure */
        EnvironmentalExposure: {
            /** Sun Hours */
            sun_hours?: number | null;
            /** Pollution Level */
            pollution_level?: string | null;
            /** Ac Exposure Hours */
            ac_exposure_hours?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LifestyleLogCreate */
        LifestyleLogCreate: {
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Water Intake Liters */
            water_intake_liters?: number | null;
            /** Stress Level */
            stress_level?: number | null;
            /** Diet Quality */
            diet_quality?: number | null;
            /** Exercise Frequency */
            exercise_frequency?: number | null;
            /** Smoking */
            smoking?: boolean | null;
            /** Alcohol Consumption */
            alcohol_consumption?: string | null;
            environmental_exposure?: components["schemas"]["EnvironmentalExposure"] | null;
        };
        /** LifestyleLogRead */
        LifestyleLogRead: {
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Water Intake Liters */
            water_intake_liters?: number | null;
            /** Stress Level */
            stress_level?: number | null;
            /** Diet Quality */
            diet_quality?: number | null;
            /** Exercise Frequency */
            exercise_frequency?: number | null;
            /** Smoking */
            smoking?: boolean | null;
            /** Alcohol Consumption */
            alcohol_consumption?: string | null;
            environmental_exposure?: components["schemas"]["EnvironmentalExposure"] | null;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
        };
        /** SkinConcernRead */
        SkinConcernRead: {
            /** Concern Id */
            concern_id: number;
            /** Concern Name */
            concern_name: string;
            /** Category */
            category: string | null;
        };
        /** SkinProfileConcernInput */
        SkinProfileConcernInput: {
            /** Concern Id */
            concern_id: number;
            /** Severity Rating */
            severity_rating: number;
            /** Priority Level */
            priority_level: number;
        };
        /** SkinProfileConcernRead */
        SkinProfileConcernRead: {
            /** Concern Id */
            concern_id: number;
            /** Severity Rating */
            severity_rating: number | null;
            /** Priority Level */
            priority_level: number | null;
        };
        /** SkinProfileCreate */
        SkinProfileCreate: {
            /** Skin Type Id */
            skin_type_id: number;
            /** Age Group */
            age_group?: string | null;
            /** Allergies */
            allergies?: string | null;
            /** Sensitivities */
            sensitivities?: string | null;
            /** Concerns */
            concerns?: components["schemas"]["SkinProfileConcernInput"][];
        };
        /** SkinProfileRead */
        SkinProfileRead: {
            /** Skin Profile Id */
            skin_profile_id: number;
            /** Skin Type Id */
            skin_type_id: number;
            /** Age Group */
            age_group: string | null;
            /** Allergies */
            allergies: string | null;
            /** Sensitivities */
            sensitivities: string | null;
            /** Concerns */
            concerns: components["schemas"]["SkinProfileConcernRead"][];
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** SkinTypeRead */
        SkinTypeRead: {
            /** Skin Type Id */
            skin_type_id: number;
            /** Skin Type Name */
            skin_type_name: string;
            /** Description */
            description: string | null;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /** Id */
            id: string;
            /** Role */
            role: string;
        };
        /** UserProfileRead */
        UserProfileRead: {
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Profile Image Url */
            profile_image_url: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Gender */
            gender: string | null;
            /** Phone Number */
            phone_number: string | null;
            /** Location */
            location: string | null;
            /** Bio */
            bio: string | null;
        };
        /**
         * UserProfileUpdate
         * @description All fields optional — PATCH-style partial update (`exclude_unset`).
         */
        UserProfileUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Profile Image Url */
            profile_image_url?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Gender */
            gender?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** Location */
            location?: string | null;
            /** Bio */
            bio?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    get_my_profile_api_v1_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileRead"];
                };
            };
        };
    };
    update_my_profile_api_v1_users_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skin_types_api_v1_skin_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinTypeRead"][];
                };
            };
        };
    };
    get_skin_concerns_api_v1_skin_concerns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinConcernRead"][];
                };
            };
        };
    };
    get_my_skin_profile_api_v1_skin_profiles_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinProfileRead"];
                };
            };
        };
    };
    create_my_skin_profile_api_v1_skin_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkinProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_my_lifestyle_log_api_v1_lifestyle_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifestyleLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifestyleLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_lifestyle_logs_api_v1_lifestyle_logs_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
}
