/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Round-trips the Better Auth JWT through FastAPI's JWKS validation — id/role
         *     come straight from the validated claims, no DB read yet (User Profile module owns
         *     the domain profile; this just proves the auth pipeline works end to end).
         */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_v1_users_me_profile_get"];
        /** Update My Profile */
        put: operations["update_my_profile_api_v1_users_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/appearance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Appearance */
        get: operations["get_my_appearance_api_v1_users_me_appearance_get"];
        /** Update My Appearance */
        put: operations["update_my_appearance_api_v1_users_me_appearance_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/appearance/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset My Appearance */
        post: operations["reset_my_appearance_api_v1_users_me_appearance_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skin Types */
        get: operations["get_skin_types_api_v1_skin_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin-concerns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skin Concerns */
        get: operations["get_skin_concerns_api_v1_skin_concerns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin-profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Skin Profile */
        get: operations["get_my_skin_profile_api_v1_skin_profiles_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create My Skin Profile */
        post: operations["create_my_skin_profile_api_v1_skin_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lifestyle-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert My Lifestyle Log */
        post: operations["upsert_my_lifestyle_log_api_v1_lifestyle_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lifestyle-logs/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Lifestyle Logs */
        get: operations["get_my_lifestyle_logs_api_v1_lifestyle_logs_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scores/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Score */
        get: operations["get_my_score_api_v1_scores_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Routines */
        get: operations["get_my_routines_api_v1_routines_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/steps/{step_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Step Completion */
        post: operations["log_step_completion_api_v1_routines_steps__step_id__log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Recommendations */
        get: operations["get_my_recommendations_api_v1_recommendations_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/me/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Progress Summary */
        get: operations["get_my_progress_summary_api_v1_progress_me_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/verification-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Verification Queue */
        get: operations["get_verification_queue_api_v1_admin_verification_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/verification-queue/{role}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Verification Review */
        get: operations["get_verification_review_api_v1_admin_verification_queue__role___user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/verification-queue/{role}/{user_id}/documents/{document_id}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Verification Document Url */
        get: operations["get_verification_document_url_api_v1_admin_verification_queue__role___user_id__documents__document_id__url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/verification-queue/{role}/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Verification */
        post: operations["approve_verification_api_v1_admin_verification_queue__role___user_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/verification-queue/{role}/{user_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Verification */
        post: operations["reject_verification_api_v1_admin_verification_queue__role___user_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/verification-queue/{role}/{user_id}/request-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request More Info */
        post: operations["request_more_info_api_v1_admin_verification_queue__role___user_id__request_info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/verification-queue/{role}/{user_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend Professional */
        post: operations["suspend_professional_api_v1_admin_verification_queue__role___user_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/verification-queue/{role}/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Professional */
        post: operations["deactivate_professional_api_v1_admin_verification_queue__role___user_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Logs */
        get: operations["get_audit_logs_api_v1_admin_audit_logs_get"];
        put?: never;
        /** Create Audit Log */
        post: operations["create_audit_log_api_v1_admin_audit_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Stats */
        get: operations["get_dashboard_stats_api_v1_admin_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingredients */
        get: operations["get_ingredients_api_v1_admin_ingredients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Products */
        get: operations["get_products_api_v1_admin_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consultant-profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_v1_consultant_profiles_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: operations["update_my_profile_api_v1_consultant_profiles_me_patch"];
        trace?: never;
    };
    "/api/v1/consultant-profiles/me/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit My Profile */
        post: operations["submit_my_profile_api_v1_consultant_profiles_me_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consultant-profiles/me/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Documents */
        get: operations["list_my_documents_api_v1_consultant_profiles_me_documents_get"];
        put?: never;
        /** Upload My Document */
        post: operations["upload_my_document_api_v1_consultant_profiles_me_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consultant-profiles/me/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete My Document */
        delete: operations["delete_my_document_api_v1_consultant_profiles_me_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dermatologist-profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_v1_dermatologist_profiles_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: operations["update_my_profile_api_v1_dermatologist_profiles_me_patch"];
        trace?: never;
    };
    "/api/v1/dermatologist-profiles/me/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit My Profile */
        post: operations["submit_my_profile_api_v1_dermatologist_profiles_me_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dermatologist-profiles/me/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Documents */
        get: operations["list_my_documents_api_v1_dermatologist_profiles_me_documents_get"];
        put?: never;
        /** Upload My Document */
        post: operations["upload_my_document_api_v1_dermatologist_profiles_me_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dermatologist-profiles/me/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete My Document */
        delete: operations["delete_my_document_api_v1_dermatologist_profiles_me_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppearancePreferenceRead */
        AppearancePreferenceRead: {
            /**
             * Palette
             * @enum {string}
             */
            palette: "default" | "emerald" | "ocean" | "lavender" | "sunset" | "slate" | "rose" | "forest";
            /**
             * Theme Mode
             * @enum {string}
             */
            theme_mode: "light" | "dark" | "system";
            /** Accent Color */
            accent_color: string | null;
            /** Font Size */
            font_size: string | null;
            /** Density */
            density: string | null;
            /** Motion Preference */
            motion_preference: string | null;
        };
        /**
         * AppearancePreferenceUpdate
         * @description All fields optional — PATCH-style partial update (`exclude_unset`), same
         *     convention as `UserProfileUpdate`. `accent_color`/`font_size`/`density`/
         *     `motion_preference` are accepted but not yet consumed by the v1 UI — genuine
         *     future-ready placeholders, not dead fields, since the column/schema/API round
         *     trip already works end to end.
         */
        AppearancePreferenceUpdate: {
            /** Palette */
            palette?: ("default" | "emerald" | "ocean" | "lavender" | "sunset" | "slate" | "rose" | "forest") | null;
            /** Theme Mode */
            theme_mode?: ("light" | "dark" | "system") | null;
            /** Accent Color */
            accent_color?: string | null;
            /** Font Size */
            font_size?: string | null;
            /** Density */
            density?: string | null;
            /** Motion Preference */
            motion_preference?: string | null;
        };
        /**
         * AuditLogCreate
         * @description Body for POST /admin/audit-logs — the one write path `audit_logs` has (this
         *     service, docs/CONVENTIONS.md's single-writer rule), used both by this service's own
         *     verification actions and by the Next.js admin role-assignment wrapper (Branch 3;
         *     Better Auth's own `set-role` action has no audit trail of its own).
         */
        AuditLogCreate: {
            /** Action */
            action: string;
            /** Target Type */
            target_type?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** AuditLogPage */
        AuditLogPage: {
            /** Items */
            items: components["schemas"]["AuditLogRead"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** AuditLogRead */
        AuditLogRead: {
            /** Audit Log Id */
            audit_log_id: number;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string | null;
            /** Target Id */
            target_id: string | null;
            /** Metadata */
            metadata_: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string | null;
        };
        /** Body_upload_my_document_api_v1_consultant_profiles_me_documents_post */
        Body_upload_my_document_api_v1_consultant_profiles_me_documents_post: {
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "government_id" | "professional_certificate" | "medical_license" | "supporting_document";
            /** File */
            file: string;
        };
        /** Body_upload_my_document_api_v1_dermatologist_profiles_me_documents_post */
        Body_upload_my_document_api_v1_dermatologist_profiles_me_documents_post: {
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "government_id" | "professional_certificate" | "medical_license" | "supporting_document";
            /** File */
            file: string;
        };
        /** ConsultantProfileDetail */
        ConsultantProfileDetail: {
            /** User Id */
            user_id: string;
            /** Profile Image Url */
            profile_image_url: string | null;
            /** Qualifications */
            qualifications: string | null;
            /** Years Of Experience */
            years_of_experience: number | null;
            /** Current Organization */
            current_organization: string | null;
            /** License Number */
            license_number: string | null;
            /** Specializations */
            specializations: string[] | null;
            /** Areas Of Expertise */
            areas_of_expertise: string[] | null;
            /** Languages */
            languages: string[] | null;
            /** Consultation Modes */
            consultation_modes: string[] | null;
            /** Availability */
            availability: string | null;
            /** Biography */
            biography: string | null;
            /** Linkedin Url */
            linkedin_url: string | null;
            /** Portfolio Url */
            portfolio_url: string | null;
            /** Clinic Address */
            clinic_address: string | null;
            /** Location */
            location: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "pending" | "approved" | "rejected" | "more_info_requested" | "suspended" | "deactivated";
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Rejection Reason */
            rejection_reason: string | null;
            /** Submitted At */
            submitted_at: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** ConsultantProfileRead */
        ConsultantProfileRead: {
            /** User Id */
            user_id: string;
            /** Profile Image Url */
            profile_image_url: string | null;
            /** Qualifications */
            qualifications: string | null;
            /** Years Of Experience */
            years_of_experience: number | null;
            /** Current Organization */
            current_organization: string | null;
            /** License Number */
            license_number: string | null;
            /** Specializations */
            specializations: string[] | null;
            /** Areas Of Expertise */
            areas_of_expertise: string[] | null;
            /** Languages */
            languages: string[] | null;
            /** Consultation Modes */
            consultation_modes: string[] | null;
            /** Availability */
            availability: string | null;
            /** Biography */
            biography: string | null;
            /** Linkedin Url */
            linkedin_url: string | null;
            /** Portfolio Url */
            portfolio_url: string | null;
            /** Clinic Address */
            clinic_address: string | null;
            /** Location */
            location: string | null;
            /** Phone */
            phone: string | null;
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "pending" | "approved" | "rejected" | "more_info_requested" | "suspended" | "deactivated";
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Rejection Reason */
            rejection_reason: string | null;
            /** Submitted At */
            submitted_at: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** ConsultantProfileSubmit */
        ConsultantProfileSubmit: {
            /** Qualifications */
            qualifications: string;
            /** Years Of Experience */
            years_of_experience: number;
            /** Current Organization */
            current_organization?: string | null;
            /** License Number */
            license_number?: string | null;
            /** Specializations */
            specializations: string[];
            /** Areas Of Expertise */
            areas_of_expertise?: string[] | null;
            /** Languages */
            languages: string[];
            /** Consultation Modes */
            consultation_modes: string[];
            /** Availability */
            availability?: string | null;
            /** Biography */
            biography: string;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            /** Clinic Address */
            clinic_address?: string | null;
            /** Location */
            location?: string | null;
            /** Phone */
            phone: string;
        };
        /**
         * ConsultantProfileUpdate
         * @description PATCH — every field optional; only supplied fields change. Never touches
         *     verification_status (that's the admin review actions' job, admin/router.py).
         */
        ConsultantProfileUpdate: {
            /** Profile Image Url */
            profile_image_url?: string | null;
            /** Qualifications */
            qualifications?: string | null;
            /** Years Of Experience */
            years_of_experience?: number | null;
            /** Current Organization */
            current_organization?: string | null;
            /** License Number */
            license_number?: string | null;
            /** Specializations */
            specializations?: string[] | null;
            /** Areas Of Expertise */
            areas_of_expertise?: string[] | null;
            /** Languages */
            languages?: string[] | null;
            /** Consultation Modes */
            consultation_modes?: string[] | null;
            /** Availability */
            availability?: string | null;
            /** Biography */
            biography?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            /** Clinic Address */
            clinic_address?: string | null;
            /** Location */
            location?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /**
         * DashboardStats
         * @description Admin dashboard (Branch 6) — real counts only, no invented KPIs. User-role
         *     counts come from Better Auth (web/app/api/admin/dashboard-stats/route.ts calls
         *     its own listUsers, not this endpoint) — this covers only what FastAPI actually
         *     owns: the verification queue and the audit trail.
         */
        DashboardStats: {
            /** Pending Consultant Count */
            pending_consultant_count: number;
            /** Pending Dermatologist Count */
            pending_dermatologist_count: number;
            /** Recent Activity */
            recent_activity: components["schemas"]["AuditLogRead"][];
        };
        /** DermatologistProfileDetail */
        DermatologistProfileDetail: {
            /** User Id */
            user_id: string;
            /** Profile Image Url */
            profile_image_url: string | null;
            /** Medical Registration Number */
            medical_registration_number: string | null;
            /** Medical Council */
            medical_council: string | null;
            /** Hospital Clinic */
            hospital_clinic: string | null;
            /** Years Of Practice */
            years_of_practice: number | null;
            /** Degrees */
            degrees: string[] | null;
            /** Board Certifications */
            board_certifications: string[] | null;
            /** Specializations */
            specializations: string[] | null;
            /** Research Interests */
            research_interests: string | null;
            /** Professional Biography */
            professional_biography: string | null;
            /** Phone */
            phone: string | null;
            /** Location */
            location: string | null;
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "pending" | "approved" | "rejected" | "more_info_requested" | "suspended" | "deactivated";
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Rejection Reason */
            rejection_reason: string | null;
            /** Submitted At */
            submitted_at: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** DermatologistProfileRead */
        DermatologistProfileRead: {
            /** User Id */
            user_id: string;
            /** Profile Image Url */
            profile_image_url: string | null;
            /** Medical Registration Number */
            medical_registration_number: string | null;
            /** Medical Council */
            medical_council: string | null;
            /** Hospital Clinic */
            hospital_clinic: string | null;
            /** Years Of Practice */
            years_of_practice: number | null;
            /** Degrees */
            degrees: string[] | null;
            /** Board Certifications */
            board_certifications: string[] | null;
            /** Specializations */
            specializations: string[] | null;
            /** Research Interests */
            research_interests: string | null;
            /** Professional Biography */
            professional_biography: string | null;
            /** Phone */
            phone: string | null;
            /** Location */
            location: string | null;
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "pending" | "approved" | "rejected" | "more_info_requested" | "suspended" | "deactivated";
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Rejection Reason */
            rejection_reason: string | null;
            /** Submitted At */
            submitted_at: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** DermatologistProfileSubmit */
        DermatologistProfileSubmit: {
            /** Medical Registration Number */
            medical_registration_number: string;
            /** Medical Council */
            medical_council: string;
            /** Hospital Clinic */
            hospital_clinic?: string | null;
            /** Years Of Practice */
            years_of_practice: number;
            /** Degrees */
            degrees: string[];
            /** Board Certifications */
            board_certifications?: string[] | null;
            /** Specializations */
            specializations: string[];
            /** Research Interests */
            research_interests?: string | null;
            /** Professional Biography */
            professional_biography: string;
            /** Phone */
            phone: string;
            /** Location */
            location?: string | null;
        };
        /**
         * DermatologistProfileUpdate
         * @description PATCH — every field optional; only supplied fields change. Never touches
         *     verification_status (that's the admin review actions' job, admin/router.py).
         */
        DermatologistProfileUpdate: {
            /** Profile Image Url */
            profile_image_url?: string | null;
            /** Medical Registration Number */
            medical_registration_number?: string | null;
            /** Medical Council */
            medical_council?: string | null;
            /** Hospital Clinic */
            hospital_clinic?: string | null;
            /** Years Of Practice */
            years_of_practice?: number | null;
            /** Degrees */
            degrees?: string[] | null;
            /** Board Certifications */
            board_certifications?: string[] | null;
            /** Specializations */
            specializations?: string[] | null;
            /** Research Interests */
            research_interests?: string | null;
            /** Professional Biography */
            professional_biography?: string | null;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
        };
        /** DocumentViewUrl */
        DocumentViewUrl: {
            /** Url */
            url: string;
        };
        /** EnvironmentalExposure */
        EnvironmentalExposure: {
            /** Sun Hours */
            sun_hours?: number | null;
            /** Pollution Level */
            pollution_level?: string | null;
            /** Ac Exposure Hours */
            ac_exposure_hours?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngredientPage
         * @description Admin's read-only Ingredient Management view (Branch 6) — full CRUD stays M3
         *     scope; this wraps ingredients.schemas.IngredientRead, not a redefinition.
         */
        IngredientPage: {
            /** Items */
            items: components["schemas"]["IngredientRead"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** IngredientRead */
        IngredientRead: {
            /** Ingredient Id */
            ingredient_id: number;
            /** Ingredient Name */
            ingredient_name: string;
            /** Inci Name */
            inci_name: string | null;
            /** Category */
            category: string | null;
            /** Is Active */
            is_active: boolean | null;
            /** Created At */
            created_at: string | null;
        };
        /** LifestyleLogCreate */
        LifestyleLogCreate: {
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Water Intake Liters */
            water_intake_liters?: number | null;
            /** Stress Level */
            stress_level?: number | null;
            /** Diet Quality */
            diet_quality?: number | null;
            /** Exercise Frequency */
            exercise_frequency?: number | null;
            /** Smoking */
            smoking?: boolean | null;
            /** Alcohol Consumption */
            alcohol_consumption?: string | null;
            environmental_exposure?: components["schemas"]["EnvironmentalExposure"] | null;
        };
        /** LifestyleLogRead */
        LifestyleLogRead: {
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Water Intake Liters */
            water_intake_liters?: number | null;
            /** Stress Level */
            stress_level?: number | null;
            /** Diet Quality */
            diet_quality?: number | null;
            /** Exercise Frequency */
            exercise_frequency?: number | null;
            /** Smoking */
            smoking?: boolean | null;
            /** Alcohol Consumption */
            alcohol_consumption?: string | null;
            environmental_exposure?: components["schemas"]["EnvironmentalExposure"] | null;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
        };
        /** PageMeta */
        PageMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * ProductPage
         * @description Admin's read-only Product Management view (Branch 6) — same reasoning as
         *     IngredientPage.
         */
        ProductPage: {
            /** Items */
            items: components["schemas"]["ProductRead"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** ProductRead */
        ProductRead: {
            /** Product Id */
            product_id: number;
            /** Brand Name */
            brand_name: string | null;
            /** Product Name */
            product_name: string | null;
            /** Category */
            category: string | null;
            /** Image Url */
            image_url: string | null;
            /** Price */
            price: number | null;
            /** Currency */
            currency: string | null;
            /** Spf Rating */
            spf_rating: number | null;
        };
        /** ProgressSummaryRead */
        ProgressSummaryRead: {
            /** Points */
            points: components["schemas"]["ScoreTrendPoint"][];
        };
        /** RecommendationRead */
        RecommendationRead: {
            product: components["schemas"]["ProductRead"];
            /** Match Score */
            match_score: number;
            /** Reasons */
            reasons: string[];
        };
        /** RoutineProductRead */
        RoutineProductRead: {
            product: components["schemas"]["ProductRead"];
            /** Usage Notes */
            usage_notes: string | null;
        };
        /** RoutineRead */
        RoutineRead: {
            /** Routine Id */
            routine_id: number;
            /** Routine Name */
            routine_name: string | null;
            /** Routine Type */
            routine_type: string | null;
            /** Description */
            description: string | null;
            /** Steps */
            steps: components["schemas"]["RoutineStepRead"][];
        };
        /** RoutineStepRead */
        RoutineStepRead: {
            /** Step Id */
            step_id: number;
            /** Step Order */
            step_order: number | null;
            /** Step Name */
            step_name: string | null;
            /** Instruction */
            instruction: string | null;
            /** Duration Minutes */
            duration_minutes: number | null;
            /** Products */
            products: components["schemas"]["RoutineProductRead"][];
            /** Completed Today */
            completed_today: boolean;
        };
        /** ScoreRead */
        ScoreRead: {
            /** Score Id */
            score_id: number;
            /** Skin Condition Score */
            skin_condition_score: number | null;
            /** Lifestyle Score */
            lifestyle_score: number | null;
            /** Sleep Quality Score */
            sleep_quality_score: number | null;
            /** Hydration Score */
            hydration_score: number | null;
            /** Routine Adherence Score */
            routine_adherence_score: number | null;
            /** Overall Score */
            overall_score: number | null;
            weights: components["schemas"]["ScoreWeightsRead"];
            /** Calculated At */
            calculated_at: string | null;
        };
        /** ScoreTrendPoint */
        ScoreTrendPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Overall Score */
            overall_score: number | null;
        };
        /** ScoreWeightsRead */
        ScoreWeightsRead: {
            /** Skin Condition Weight */
            skin_condition_weight: number;
            /** Lifestyle Weight */
            lifestyle_weight: number;
            /** Sleep Quality Weight */
            sleep_quality_weight: number;
            /** Routine Adherence Weight */
            routine_adherence_weight: number;
            /** Hydration Weight */
            hydration_weight: number;
        };
        /** SkinConcernRead */
        SkinConcernRead: {
            /** Concern Id */
            concern_id: number;
            /** Concern Name */
            concern_name: string;
            /** Category */
            category: string | null;
        };
        /** SkinProfileConcernInput */
        SkinProfileConcernInput: {
            /** Concern Id */
            concern_id: number;
            /** Severity Rating */
            severity_rating: number;
            /** Priority Level */
            priority_level: number;
        };
        /** SkinProfileConcernRead */
        SkinProfileConcernRead: {
            /** Concern Id */
            concern_id: number;
            /** Severity Rating */
            severity_rating: number | null;
            /** Priority Level */
            priority_level: number | null;
        };
        /** SkinProfileCreate */
        SkinProfileCreate: {
            /** Skin Type Id */
            skin_type_id: number;
            /** Age Group */
            age_group?: string | null;
            /** Allergies */
            allergies?: string | null;
            /** Sensitivities */
            sensitivities?: string | null;
            /** Concerns */
            concerns?: components["schemas"]["SkinProfileConcernInput"][];
        };
        /** SkinProfileRead */
        SkinProfileRead: {
            /** Skin Profile Id */
            skin_profile_id: number;
            /** Skin Type Id */
            skin_type_id: number;
            /** Age Group */
            age_group: string | null;
            /** Allergies */
            allergies: string | null;
            /** Sensitivities */
            sensitivities: string | null;
            /** Concerns */
            concerns: components["schemas"]["SkinProfileConcernRead"][];
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** SkinTypeRead */
        SkinTypeRead: {
            /** Skin Type Id */
            skin_type_id: number;
            /** Skin Type Name */
            skin_type_name: string;
            /** Description */
            description: string | null;
        };
        /** StepCompletionUpdate */
        StepCompletionUpdate: {
            /** Completed */
            completed: boolean;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /** Id */
            id: string;
            /** Role */
            role: string;
        };
        /** UserProfileRead */
        UserProfileRead: {
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Profile Image Url */
            profile_image_url: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Gender */
            gender: string | null;
            /** Phone Number */
            phone_number: string | null;
            /** Location */
            location: string | null;
            /** Bio */
            bio: string | null;
        };
        /**
         * UserProfileUpdate
         * @description All fields optional — PATCH-style partial update (`exclude_unset`).
         */
        UserProfileUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Profile Image Url */
            profile_image_url?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Gender */
            gender?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** Location */
            location?: string | null;
            /** Bio */
            bio?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationActionRequest
         * @description approve / deactivate — a reason is useful but not required.
         */
        VerificationActionRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * VerificationActionWithReasonRequest
         * @description reject / request-info / suspend — a real reason is the whole point of the
         *     action (the professional reads it back on their locked dashboard).
         */
        VerificationActionWithReasonRequest: {
            /** Reason */
            reason: string;
        };
        /** VerificationQueueItem */
        VerificationQueueItem: {
            /** User Id */
            user_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "consultant" | "dermatologist";
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "pending" | "approved" | "rejected" | "more_info_requested" | "suspended" | "deactivated";
            /** Submitted At */
            submitted_at: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
        };
        /** VerificationQueuePage */
        VerificationQueuePage: {
            /** Items */
            items: components["schemas"]["VerificationQueueItem"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** VerificationReviewDetail */
        VerificationReviewDetail: {
            /**
             * Role
             * @enum {string}
             */
            role: "consultant" | "dermatologist";
            /** Profile */
            profile: components["schemas"]["ConsultantProfileDetail"] | components["schemas"]["DermatologistProfileDetail"];
            /** Documents */
            documents: components["schemas"]["app__services__admin__schemas__VerificationDocumentRead"][];
        };
        /** VerificationDocumentRead */
        app__services__admin__schemas__VerificationDocumentRead: {
            /** Document Id */
            document_id: number;
            /** Document Type */
            document_type: string;
            /** Original Filename */
            original_filename: string | null;
            /** Uploaded At */
            uploaded_at: string | null;
            /** Verified At */
            verified_at: string | null;
        };
        /** VerificationDocumentRead */
        app__services__consultant_profile__schemas__VerificationDocumentRead: {
            /** Document Id */
            document_id: number;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "government_id" | "professional_certificate" | "medical_license" | "supporting_document";
            /** Original Filename */
            original_filename: string | null;
            /** Uploaded At */
            uploaded_at: string | null;
            /** Verified At */
            verified_at: string | null;
        };
        /** VerificationDocumentRead */
        app__services__dermatologist_profile__schemas__VerificationDocumentRead: {
            /** Document Id */
            document_id: number;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "government_id" | "professional_certificate" | "medical_license" | "supporting_document";
            /** Original Filename */
            original_filename: string | null;
            /** Uploaded At */
            uploaded_at: string | null;
            /** Verified At */
            verified_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    get_my_profile_api_v1_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileRead"];
                };
            };
        };
    };
    update_my_profile_api_v1_users_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_appearance_api_v1_users_me_appearance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearancePreferenceRead"];
                };
            };
        };
    };
    update_my_appearance_api_v1_users_me_appearance_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppearancePreferenceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearancePreferenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_my_appearance_api_v1_users_me_appearance_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearancePreferenceRead"];
                };
            };
        };
    };
    get_skin_types_api_v1_skin_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinTypeRead"][];
                };
            };
        };
    };
    get_skin_concerns_api_v1_skin_concerns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinConcernRead"][];
                };
            };
        };
    };
    get_my_skin_profile_api_v1_skin_profiles_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinProfileRead"];
                };
            };
        };
    };
    create_my_skin_profile_api_v1_skin_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkinProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_my_lifestyle_log_api_v1_lifestyle_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifestyleLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifestyleLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_lifestyle_logs_api_v1_lifestyle_logs_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifestyleLogRead"][];
                };
            };
        };
    };
    get_my_score_api_v1_scores_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreRead"];
                };
            };
        };
    };
    get_my_routines_api_v1_routines_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineRead"][];
                };
            };
        };
    };
    log_step_completion_api_v1_routines_steps__step_id__log_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                step_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepCompletionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_recommendations_api_v1_recommendations_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"][];
                };
            };
        };
    };
    get_my_progress_summary_api_v1_progress_me_summary_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verification_queue_api_v1_admin_verification_queue_get: {
        parameters: {
            query?: {
                role?: ("consultant" | "dermatologist") | null;
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationQueuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verification_review_api_v1_admin_verification_queue__role___user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "consultant" | "dermatologist";
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationReviewDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verification_document_url_api_v1_admin_verification_queue__role___user_id__documents__document_id__url_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "consultant" | "dermatologist";
                user_id: string;
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentViewUrl"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_verification_api_v1_admin_verification_queue__role___user_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "consultant" | "dermatologist";
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantProfileDetail"] | components["schemas"]["DermatologistProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_verification_api_v1_admin_verification_queue__role___user_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "consultant" | "dermatologist";
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationActionWithReasonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantProfileDetail"] | components["schemas"]["DermatologistProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_more_info_api_v1_admin_verification_queue__role___user_id__request_info_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "consultant" | "dermatologist";
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationActionWithReasonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantProfileDetail"] | components["schemas"]["DermatologistProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_professional_api_v1_admin_verification_queue__role___user_id__suspend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "consultant" | "dermatologist";
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationActionWithReasonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantProfileDetail"] | components["schemas"]["DermatologistProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_professional_api_v1_admin_verification_queue__role___user_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "consultant" | "dermatologist";
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantProfileDetail"] | components["schemas"]["DermatologistProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_logs_api_v1_admin_audit_logs_get: {
        parameters: {
            query?: {
                action?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_audit_log_api_v1_admin_audit_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stats_api_v1_admin_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    get_ingredients_api_v1_admin_ingredients_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_products_api_v1_admin_products_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_profile_api_v1_consultant_profiles_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantProfileRead"];
                };
            };
        };
    };
    update_my_profile_api_v1_consultant_profiles_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultantProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_my_profile_api_v1_consultant_profiles_me_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultantProfileSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultantProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_documents_api_v1_consultant_profiles_me_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__services__consultant_profile__schemas__VerificationDocumentRead"][];
                };
            };
        };
    };
    upload_my_document_api_v1_consultant_profiles_me_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_my_document_api_v1_consultant_profiles_me_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__services__consultant_profile__schemas__VerificationDocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_document_api_v1_consultant_profiles_me_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_profile_api_v1_dermatologist_profiles_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DermatologistProfileRead"];
                };
            };
        };
    };
    update_my_profile_api_v1_dermatologist_profiles_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DermatologistProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DermatologistProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_my_profile_api_v1_dermatologist_profiles_me_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DermatologistProfileSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DermatologistProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_documents_api_v1_dermatologist_profiles_me_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__services__dermatologist_profile__schemas__VerificationDocumentRead"][];
                };
            };
        };
    };
    upload_my_document_api_v1_dermatologist_profiles_me_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_my_document_api_v1_dermatologist_profiles_me_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__services__dermatologist_profile__schemas__VerificationDocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_document_api_v1_dermatologist_profiles_me_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
