-- Skinlytics PostgreSQL Schema (v3 — Better Auth aligned)
-- Core transactional database.
--
-- Changelog vs v2 (see schemas/README_v3_changes.md and ADR-002/003):
--   * Identity is now owned by Better Auth (Next.js). The v2 `users` and `oauth_accounts`
--     tables are REMOVED and replaced by Better-Auth-managed tables: user, session,
--     account, verification, jwks — generated by `npx @better-auth/cli generate`
--     (shown below for reference / FK targets only; do NOT hand-edit them).
--   * The v2 `roles` table + `users.role_id` FK are REMOVED. Roles live on the Better Auth
--     `user.role` column (admin plugin): 'user' | 'consultant' | 'dermatologist' | 'admin'.
--   * Every domain user_id / consultant_id is now TEXT REFERENCES "user"(id)
--     (Better Auth uses string IDs). This is the main v2 -> v3 change.
--   * All other domain tables (skin taxonomy, ingredients + junctions, routines/products,
--     scoring, progress, consulting, notifications/billing, indexes) are unchanged except
--     the id type of the user references.

-- ============================================================
-- BETTER AUTH IDENTITY TABLES  (generated by the Better Auth CLI — reference only)
-- Exact columns depend on enabled plugins/version. Better Auth defaults to camelCase
-- identifiers and string (text) primary keys. Run `npx @better-auth/cli generate`
-- to produce/update these; do not maintain them by hand.
-- ============================================================

CREATE TABLE "user" (
    id             TEXT PRIMARY KEY,                 -- 32-char string id (Better Auth)
    name           TEXT,
    email          TEXT UNIQUE NOT NULL,
    "emailVerified" BOOLEAN DEFAULT FALSE,
    image          TEXT,
    role           TEXT DEFAULT 'user'               -- admin plugin: user|consultant|dermatologist|admin
        CHECK (role IN ('user','consultant','dermatologist','admin')),
    banned         BOOLEAN DEFAULT FALSE,
    "banReason"    TEXT,
    "banExpires"   TIMESTAMP,
    "createdAt"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Consent ledger (docs/SUGGESTIONS.md P0, docs/WIREFRAMES.md Registration accept
    -- criteria) — added via `npx @better-auth/cli generate/migrate` as Better Auth
    -- `user.additionalFields` (web/lib/auth.ts), not Alembic (ADR-003: identity tables
    -- are Better-Auth-owned). Null for accounts created before this field existed and
    -- for Google OAuth signups, which don't go through the consent checkbox.
    "consentAcceptedAt"    TIMESTAMPTZ,
    "consentPolicyVersion" TEXT
);

CREATE TABLE session (
    id               TEXT PRIMARY KEY,
    "userId"         TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    token            TEXT UNIQUE NOT NULL,
    "expiresAt"      TIMESTAMP NOT NULL,
    "ipAddress"      TEXT,
    "userAgent"      TEXT,
    "impersonatedBy" TEXT,                            -- admin plugin
    "createdAt"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE account (
    id                      TEXT PRIMARY KEY,
    "userId"                TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    "accountId"             TEXT NOT NULL,            -- provider's user id, or the user id for email/pw
    "providerId"            TEXT NOT NULL,            -- 'credential' | 'google' | 'facebook' | 'apple'
    "accessToken"           TEXT,
    "refreshToken"          TEXT,
    "idToken"               TEXT,
    "accessTokenExpiresAt"  TIMESTAMP,
    "refreshTokenExpiresAt" TIMESTAMP,
    scope                   TEXT,
    password                TEXT,                     -- scrypt hash for email/password accounts
    "createdAt"             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE verification (
    id           TEXT PRIMARY KEY,
    identifier   TEXT NOT NULL,
    value        TEXT NOT NULL,
    "expiresAt"  TIMESTAMP NOT NULL,
    "createdAt"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE jwks (                                   -- Better Auth JWT plugin (JWKS keys)
    id           TEXT PRIMARY KEY,
    "publicKey"  TEXT NOT NULL,
    "privateKey" TEXT NOT NULL,
    "createdAt"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- DOMAIN: user profile (extends Better Auth user with app-specific fields)
-- ============================================================

CREATE TABLE user_profiles (
    profile_id SERIAL PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    profile_image_url VARCHAR(255),
    date_of_birth DATE,
    gender VARCHAR(20),
    phone_number VARCHAR(20),
    location VARCHAR(150),
    bio TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- SKIN TAXONOMY
-- ============================================================

CREATE TABLE skin_types (
    skin_type_id SERIAL PRIMARY KEY,
    skin_type_name VARCHAR(50) UNIQUE,
    description TEXT
);

CREATE TABLE skin_profiles (
    skin_profile_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    skin_type_id INTEGER NOT NULL REFERENCES skin_types(skin_type_id),
    age_group VARCHAR(50),
    allergies TEXT,
    sensitivities TEXT,
    is_current BOOLEAN DEFAULT TRUE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE skin_concerns (
    concern_id SERIAL PRIMARY KEY,
    concern_name VARCHAR(100) UNIQUE,
    description TEXT,
    category VARCHAR(100)
);

CREATE TABLE skin_profile_concerns (
    profile_concern_id SERIAL PRIMARY KEY,
    skin_profile_id INTEGER NOT NULL REFERENCES skin_profiles(skin_profile_id) ON DELETE CASCADE,
    concern_id INTEGER NOT NULL REFERENCES skin_concerns(concern_id),
    severity_rating INTEGER CHECK (severity_rating BETWEEN 1 AND 10),
    priority_level INTEGER CHECK (priority_level BETWEEN 1 AND 10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- INGREDIENTS (relational source of truth; replaces the dropped graph DB — ADR-001)
-- ============================================================

CREATE TABLE ingredients (
    ingredient_id SERIAL PRIMARY KEY,
    ingredient_name VARCHAR(150) UNIQUE NOT NULL,
    inci_name VARCHAR(150),
    category VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ingredient_concern_treats (
    id SERIAL PRIMARY KEY,
    ingredient_id INTEGER NOT NULL REFERENCES ingredients(ingredient_id) ON DELETE CASCADE,
    concern_id INTEGER NOT NULL REFERENCES skin_concerns(concern_id) ON DELETE CASCADE,
    evidence_strength VARCHAR(20) DEFAULT 'moderate'
        CHECK (evidence_strength IN ('weak', 'moderate', 'strong')),
    UNIQUE (ingredient_id, concern_id)
);

CREATE TABLE ingredient_skintype_avoid (
    id SERIAL PRIMARY KEY,
    ingredient_id INTEGER NOT NULL REFERENCES ingredients(ingredient_id) ON DELETE CASCADE,
    skin_type_id INTEGER NOT NULL REFERENCES skin_types(skin_type_id) ON DELETE CASCADE,
    reason TEXT,
    UNIQUE (ingredient_id, skin_type_id)
);

-- Milestone 2 P7 (MILESTONE 2.docx §2, docs/DECISIONS.md ADR-026): the allergy list
-- is structured ingredient ids, not free text, so P12's allergy detection can match
-- against it directly. skin_profiles.allergies (TEXT) stays as-is, unchanged and
-- deprecated (a pre-existing column, not dropped — no destructive migration), for
-- any free-text note a structured ingredient id can't capture.
CREATE TABLE skin_profile_allergies (
    profile_allergy_id SERIAL PRIMARY KEY,
    skin_profile_id INTEGER NOT NULL REFERENCES skin_profiles(skin_profile_id) ON DELETE CASCADE,
    ingredient_id INTEGER NOT NULL REFERENCES ingredients(ingredient_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (skin_profile_id, ingredient_id)
);

-- ============================================================
-- ROUTINES & PRODUCTS
-- ============================================================

CREATE TABLE skincare_routines (
    routine_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    routine_name VARCHAR(100),
    routine_type VARCHAR(50),
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    generated_by_ai BOOLEAN DEFAULT TRUE,
    score_id INTEGER REFERENCES skin_assessments(score_id),  -- nullable, best-effort: the
        -- most recently computed score at generation time (Milestone 2 Step 1.1's
        -- "assessment_id" traceability; migration f2a6c1d09b3e)
    skin_profile_id INTEGER REFERENCES skin_profiles(skin_profile_id),  -- M2-P11: which
        -- profile *version* this routine was generated against — lets
        -- get_or_generate_routines detect a re-assessment (a new profile version) and
        -- regenerate, the same way a season change already regenerates Seasonal Care.
        -- Nullable: routines generated before this column existed have no value here.
    created_by_professional_id TEXT REFERENCES "user"(id) ON DELETE SET NULL,  -- ADR-050: NULL = AI-generated
        -- (the existing engine, unchanged). Non-NULL = the consultant/dermatologist
        -- user_id who authored this routine. Author, not owner — user_id above stays
        -- the client the routine belongs to either way. Migration 5f6e0ea439c6.
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE routine_steps (
    step_id SERIAL PRIMARY KEY,
    routine_id INTEGER NOT NULL REFERENCES skincare_routines(routine_id) ON DELETE CASCADE,
    step_order INTEGER,
    step_name VARCHAR(100),
    category VARCHAR(50),  -- M2-P11: one of the 6 canonical categories (Cleansing,
        -- Exfoliation, Treatment, Moisturizing, Sun Protection, Night Care) — distinct
        -- from products.category (the real, smaller product taxonomy candidates are
        -- drawn from; routines/constants.py maps between the two).
    instruction TEXT,
    rationale TEXT,  -- M2-P11: why this product was chosen (concern match, category fit)
    safety_flag VARCHAR(100),  -- M2-P11: which guardrail fired for this step, if any
        -- (e.g. "soothing_substitution") — NULL when no guardrail intervened.
    duration_minutes INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    product_id SERIAL PRIMARY KEY,
    brand_name VARCHAR(100),
    product_name VARCHAR(150),
    category VARCHAR(100),
    product_url VARCHAR(255),
    image_url VARCHAR(255),
    price DECIMAL(10,2),
    currency VARCHAR(10),
    volume_ml INTEGER,
    spf_rating INTEGER,
    -- M3-C (migration 103dadbc13ce): real Sephora product_info.csv columns
    -- (rating, reviews) -- nullable, curated seed rows have neither.
    rating DECIMAL(3,2),
    review_count INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ADR-043: multiple images per product (products.image_url is a single S3-key
-- column, ADR-040/041, and can't hold this). Direct external URLs, rendered
-- as-is, never re-hosted -- owner decision 2026-08-03 for this catalog subset.
CREATE TABLE product_images (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    image_url VARCHAR(500) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    UNIQUE (product_id, image_url)
);

CREATE TABLE product_ingredients (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    ingredient_id INTEGER NOT NULL REFERENCES ingredients(ingredient_id),
    concentration_notes VARCHAR(100),
    UNIQUE (product_id, ingredient_id)
);

CREATE TABLE product_skin_types (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    skin_type_id INTEGER NOT NULL REFERENCES skin_types(skin_type_id),
    UNIQUE (product_id, skin_type_id)
);

CREATE TABLE product_concerns (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    concern_id INTEGER NOT NULL REFERENCES skin_concerns(concern_id),
    UNIQUE (product_id, concern_id)
);

CREATE TABLE routine_products (
    routine_product_id SERIAL PRIMARY KEY,
    routine_id INTEGER NOT NULL REFERENCES skincare_routines(routine_id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(product_id),
    step_id INTEGER REFERENCES routine_steps(step_id),
    usage_notes TEXT
);

-- ============================================================
-- SCORING & PROGRESS
-- ============================================================

CREATE TABLE scoring_weights (
    weight_id SERIAL PRIMARY KEY,
    skin_condition_weight DECIMAL(4,2) NOT NULL DEFAULT 0.35,
    lifestyle_weight DECIMAL(4,2) NOT NULL DEFAULT 0.20,
    sleep_quality_weight DECIMAL(4,2) NOT NULL DEFAULT 0.15,
    routine_adherence_weight DECIMAL(4,2) NOT NULL DEFAULT 0.20,
    hydration_weight DECIMAL(4,2) NOT NULL DEFAULT 0.10,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_weights_sum CHECK (
        skin_condition_weight + lifestyle_weight + sleep_quality_weight
        + routine_adherence_weight + hydration_weight = 1.00
    )
);

CREATE TABLE ingredient_safety_config (
    config_id SERIAL PRIMARY KEY,
    avoid_deduction DECIMAL(5,2) NOT NULL DEFAULT 40.0,
    caution_deduction DECIMAL(5,2) NOT NULL DEFAULT 15.0,
    allergy_deduction DECIMAL(5,2) NOT NULL DEFAULT 50.0,
    safe_threshold DECIMAL(5,2) NOT NULL DEFAULT 80.0,
    warning_threshold DECIMAL(5,2) NOT NULL DEFAULT 50.0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_safety_thresholds_ordered CHECK (safe_threshold > warning_threshold)
);

CREATE UNIQUE INDEX uq_ingredient_safety_config_one_active
    ON ingredient_safety_config (is_active)
    WHERE is_active = true;

CREATE TABLE recommendation_weights (
    weight_id SERIAL PRIMARY KEY,
    concern_weight DECIMAL(4,2) NOT NULL DEFAULT 0.50,
    skin_type_fit_weight DECIMAL(4,2) NOT NULL DEFAULT 0.35,
    rating_weight DECIMAL(4,2) NOT NULL DEFAULT 0.15,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_recommendation_weights_sum CHECK (
        concern_weight + skin_type_fit_weight + rating_weight = 1.00
    )
);
CREATE UNIQUE INDEX uq_recommendation_weights_one_active ON recommendation_weights (is_active) WHERE is_active = true;

CREATE TABLE skin_assessments (
    score_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    skin_condition_score DECIMAL(5,2),
    lifestyle_score DECIMAL(5,2),
    sleep_quality_score DECIMAL(5,2),
    hydration_score DECIMAL(5,2),
    routine_adherence_score DECIMAL(5,2),
    overall_score DECIMAL(5,2),
    weight_id INTEGER REFERENCES scoring_weights(weight_id),
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Milestone 2 P9 (MILESTONE 2.docx "4. Core Backend API Endpoints") — the
-- immutable raw snapshot POST /api/v1/assessment/submit persists. Append-only:
-- a re-assessment writes a new row, never an update. Separate from
-- skin_assessments (the computed score row) and skin_profiles (the current
-- profile) — this is the audit trail of what was actually submitted, verbatim.
CREATE TABLE assessment_submissions (
    submission_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    schema_version INTEGER NOT NULL DEFAULT 1,
    raw_payload JSONB NOT NULL,
    score_id INTEGER REFERENCES skin_assessments(score_id),
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_assessment_submissions_user ON assessment_submissions(user_id);

CREATE TABLE progress_reports (
    report_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    report_type VARCHAR(50),
    summary TEXT,
    report_url VARCHAR(255),
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_progress_reports_user_generated ON progress_reports(user_id, generated_at);

CREATE TABLE progress_images (
    progress_image_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    image_url VARCHAR(255),
    image_stage VARCHAR(50),
    skin_health_score_at_upload DECIMAL(5,2),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_recommendations (
    recommendation_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(product_id),
    recommendation_score DECIMAL(5,2),
    recommendation_reason TEXT,
    recommended_by_professional_id TEXT REFERENCES "user"(id) ON DELETE SET NULL,  -- ADR-051:
        -- NULL = system-served (get_recommendations' own pipeline). Non-NULL = the
        -- consultant/dermatologist who assigned it directly.
    usage_instructions TEXT,   -- ADR-051, consultant-assigned only
    frequency VARCHAR(50),     -- ADR-051, consultant-assigned only
    is_active BOOLEAN DEFAULT TRUE,  -- ADR-051, meaningful for consultant-assigned rows
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- CONSULTING  (consultant_id and user_id both reference Better Auth "user")
-- ============================================================

CREATE TABLE consultant_clients (
    assignment_id SERIAL PRIMARY KEY,
    consultant_id TEXT NOT NULL REFERENCES "user"(id),
    user_id TEXT NOT NULL REFERENCES "user"(id),
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'paused', 'ended')),
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (consultant_id, user_id)
);

CREATE TABLE consultant_notes (
    note_id SERIAL PRIMARY KEY,
    consultant_id TEXT NOT NULL REFERENCES "user"(id),
    user_id TEXT NOT NULL REFERENCES "user"(id),
    note_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- PROFESSIONAL VERIFICATION (Consultant / Dermatologist onboarding + admin review)
-- v3.1 addition — Milestone 1 foundation expansion. Consultant and Dermatologist are
-- professional roles (AGENTS.md), not consumer signups: after registering, each
-- submits a role-specific profile and supporting documents, then sits in
-- verification_status = 'pending' until an admin reviews it (audit_logs records every
-- transition). Two separate tables, not one polymorphic table, because the field sets
-- genuinely differ (medical registration/council vs. license number/consultation
-- modes) and neither role's fields are optional decoration on the other's schema.
-- ============================================================

CREATE TABLE consultant_profiles (
    consultant_profile_id SERIAL PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    profile_image_url VARCHAR(255),
    qualifications TEXT,
    years_of_experience INTEGER,
    current_organization VARCHAR(200),
    license_number VARCHAR(100),
    specializations TEXT[],
    areas_of_expertise TEXT[],
    languages TEXT[],
    consultation_modes TEXT[],
    availability TEXT,
    biography TEXT,
    linkedin_url VARCHAR(255),
    portfolio_url VARCHAR(255),
    clinic_address TEXT,
    location VARCHAR(150),
    phone VARCHAR(20),
    verification_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (verification_status IN
            ('pending', 'approved', 'rejected', 'more_info_requested', 'suspended', 'deactivated')),
    reviewed_by TEXT REFERENCES "user"(id),
    reviewed_at TIMESTAMP,
    rejection_reason TEXT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dermatologist_profiles (
    dermatologist_profile_id SERIAL PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    profile_image_url VARCHAR(255),
    medical_registration_number VARCHAR(100),
    medical_council VARCHAR(150),
    hospital_clinic VARCHAR(200),
    years_of_practice INTEGER,
    degrees TEXT[],
    board_certifications TEXT[],
    specializations TEXT[],
    research_interests TEXT,
    professional_biography TEXT,
    consultation_modes TEXT[],
    phone VARCHAR(20),
    location VARCHAR(150),
    verification_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (verification_status IN
            ('pending', 'approved', 'rejected', 'more_info_requested', 'suspended', 'deactivated')),
    reviewed_by TEXT REFERENCES "user"(id),
    reviewed_at TIMESTAMP,
    rejection_reason TEXT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Polymorphic across both profile types (owner_user_id, not a profile FK) so one
-- table serves government ID / certificate / license / supporting-document uploads
-- for either role without a second near-identical table. storage_key is the object
-- key in the S3-compatible store (backend/app/core/storage.py), never a raw
-- filesystem path — signed URLs are generated on read, never stored.
CREATE TABLE verification_documents (
    document_id SERIAL PRIMARY KEY,
    owner_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    document_type VARCHAR(30) NOT NULL
        CHECK (document_type IN
            ('government_id', 'professional_certificate', 'medical_license', 'supporting_document')),
    storage_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    verified_by TEXT REFERENCES "user"(id),
    verified_at TIMESTAMP
);

-- ============================================================
-- APPOINTMENTS (Milestone 3 scheduling subsystem)
-- ============================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE provider_availability (
    availability_id SERIAL PRIMARY KEY,
    provider_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    slot_duration_minutes SMALLINT NOT NULL DEFAULT 30,
    CHECK (day_of_week BETWEEN 0 AND 6),
    CHECK (end_time > start_time)
);

CREATE TABLE availability_exceptions (
    exception_id SERIAL PRIMARY KEY,
    provider_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    exception_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    reason TEXT,
    CHECK ((start_time IS NULL) = (end_time IS NULL))
);

CREATE TABLE appointments (
    appointment_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id),
    provider_id TEXT NOT NULL REFERENCES "user"(id),
    provider_role VARCHAR(20) NOT NULL,
    consultation_mode VARCHAR(20) NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    cancelled_by TEXT REFERENCES "user"(id),
    cancellation_reason TEXT,
    original_start_time TIMESTAMPTZ,
    notes TEXT,
    concern TEXT,
    meeting_link TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (provider_role IN ('consultant', 'dermatologist')),
    CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
    EXCLUDE USING gist (
        provider_id WITH =,
        tstzrange(start_time, end_time) WITH &&
    ) WHERE (status IN ('pending', 'confirmed'))
);

-- General-purpose system audit log — serves the Admin platform's "Audit Logs" /
-- "Activity Logs" screens and every verification-workflow transition
-- (submitted/approved/rejected/more_info_requested/suspended/deactivated/
-- role_changed/banned/...). metadata is the one JSONB column in this schema by
-- design: an event log is genuinely unstructured per action, unlike the typed
-- relational tables above.
CREATE TABLE audit_logs (
    audit_log_id SERIAL PRIMARY KEY,
    actor_user_id TEXT REFERENCES "user"(id),
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(50),
    target_id TEXT,
    metadata JSONB,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- NOTIFICATIONS & BILLING
-- ============================================================

CREATE TABLE notifications (
    notification_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    title VARCHAR(150),
    message TEXT,
    notification_type VARCHAR(50),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reminders (
    reminder_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    reminder_type VARCHAR(50),
    title VARCHAR(150),
    message TEXT,
    reminder_time TIME,
    frequency VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Backs the Reports page's "Scheduled Automations" card (M3-Reports/Reminders,
-- 2026-08-12) — recurring report generation via an arq cron job. report_type mirrors
-- report_schedules' own literal set ('assessment' | 'progress' | 'routine'); frequency
-- is 'weekly' (uses day_of_week) or 'monthly' (uses day_of_month), never both set.
CREATE TABLE report_schedules (
    schedule_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    report_type VARCHAR(50) NOT NULL,
    frequency VARCHAR(20) NOT NULL CHECK (frequency IN ('weekly', 'monthly')),
    day_of_week SMALLINT,
    day_of_month SMALLINT,
    time_of_day TIME NOT NULL DEFAULT '08:00:00',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subscriptions (
    subscription_id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    plan_name VARCHAR(100),
    price DECIMAL(10,2),
    billing_cycle VARCHAR(50),
    start_date DATE,
    end_date DATE,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payments (
    payment_id SERIAL PRIMARY KEY,
    subscription_id INTEGER REFERENCES subscriptions(subscription_id),
    user_id TEXT NOT NULL REFERENCES "user"(id),
    gateway VARCHAR(20) CHECK (gateway IN ('stripe', 'razorpay')),
    gateway_transaction_id VARCHAR(255) UNIQUE,
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    status VARCHAR(20) DEFAULT 'pending'
        CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- APPEARANCE PREFERENCES (Theme system, Phase 3)
-- ============================================================

-- One row per user, any role — a Consultant/Dermatologist/Admin account needs a
-- theme just as much as a User does, so this references "user" directly rather than
-- going through the User-role-only `user_profiles` table. `palette` is the token-
-- *value* set (docs/DESIGN.md's locked Frosted Lab Glass system — spacing, radius,
-- typography, glass rules — stays fixed across every palette; only the semantic
-- color tokens a palette defines vary). `theme_mode` is orthogonal light/dark/system,
-- mirroring next-themes' own three-value model. accent_color/font_size/density/
-- motion_preference are genuine future-ready placeholders (nullable, unused by the
-- v1 UI), not implemented speculatively.
CREATE TABLE user_appearance_preferences (
    preference_id SERIAL PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    palette VARCHAR(20) NOT NULL DEFAULT 'default'
        CHECK (palette IN
            ('default', 'emerald', 'ocean', 'lavender', 'sunset', 'slate', 'rose', 'forest')),
    theme_mode VARCHAR(10) NOT NULL DEFAULT 'system'
        CHECK (theme_mode IN ('light', 'dark', 'system')),
    accent_color VARCHAR(20),
    font_size VARCHAR(10),
    density VARCHAR(10),
    motion_preference VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- OUTBOX (ADR-010, M3-A — transactional outbox for ES/vector projection)
-- ============================================================

-- Writes to products/ingredients/knowledge_articles/skin_profiles append a row here
-- in the same Postgres transaction as the source mutation (knowledge_articles is
-- Mongo-owned, so its append is best-effort immediately after the Mongo write
-- commits, not truly atomic). The arq worker (backend/app/worker/) polls
-- `processed_at IS NULL` and projects to Elasticsearch + FAISS/Pinecone; nothing
-- else ever writes those derived stores directly (single-writer rule, ADR-005).
CREATE TABLE outbox (
    outbox_id BIGSERIAL PRIMARY KEY,
    aggregate_type VARCHAR(50) NOT NULL,   -- 'product'|'ingredient'|'article'|'profile'
    aggregate_id TEXT NOT NULL,            -- TEXT: covers int PKs and user ids (ADR-003)
    event_type VARCHAR(50) NOT NULL,       -- 'upsert'|'delete'
    payload JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP                 -- NULL = pending
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_session_user ON session("userId");
CREATE INDEX idx_account_user ON account("userId");
CREATE INDEX idx_user_profiles_user ON user_profiles(user_id);
CREATE INDEX idx_skin_profiles_user ON skin_profiles(user_id);
CREATE INDEX idx_skin_profile_concerns_profile ON skin_profile_concerns(skin_profile_id);
CREATE INDEX idx_routines_user ON skincare_routines(user_id);
CREATE INDEX idx_routines_user_active ON skincare_routines(user_id, is_active);
CREATE INDEX idx_routine_steps_routine ON routine_steps(routine_id);
CREATE INDEX idx_product_ingredients_product ON product_ingredients(product_id);
CREATE INDEX idx_product_ingredients_ingredient ON product_ingredients(ingredient_id);
CREATE INDEX idx_product_skin_types_product ON product_skin_types(product_id);
CREATE INDEX idx_product_concerns_product ON product_concerns(product_id);
CREATE INDEX idx_skin_scores_user_time ON skin_assessments(user_id, calculated_at);
CREATE INDEX idx_progress_images_user ON progress_images(user_id);
CREATE INDEX idx_product_recommendations_user ON product_recommendations(user_id);
CREATE INDEX idx_consultant_clients_consultant ON consultant_clients(consultant_id);
CREATE INDEX idx_consultant_notes_user ON consultant_notes(user_id);
CREATE INDEX idx_consultant_profiles_status ON consultant_profiles(verification_status);
CREATE INDEX idx_dermatologist_profiles_status ON dermatologist_profiles(verification_status);
CREATE INDEX idx_verification_documents_owner ON verification_documents(owner_user_id);
CREATE INDEX idx_audit_logs_actor ON audit_logs(actor_user_id);
CREATE INDEX idx_audit_logs_target ON audit_logs(target_type, target_id);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at);
CREATE INDEX idx_notifications_user_unread ON notifications(user_id, is_read);
CREATE INDEX idx_reminders_user_active ON reminders(user_id, is_active);
CREATE INDEX ix_report_schedules_user_id ON report_schedules(user_id);
CREATE INDEX idx_subscriptions_user_status ON subscriptions(user_id, status);
CREATE INDEX idx_payments_user ON payments(user_id);
-- Production-readiness audit (migration c4f7e1a92d3b): routine_products had no
-- index beyond its own PK despite being queried by step_id on every routine read;
-- routine_id indexed too for the ON DELETE CASCADE FK's own lookup efficiency.
-- products.category has no supporting index either -- masked by the small seed
-- catalog today, a real cost once the real Kaggle product pipeline runs.
CREATE INDEX idx_routine_products_step ON routine_products(step_id);
CREATE INDEX idx_routine_products_routine ON routine_products(routine_id);
CREATE INDEX idx_products_category ON products(category);
-- migration 2d9fcee3b312 (M3-A): the worker polls pending outbox rows in FIFO order.
CREATE INDEX idx_outbox_processed_id ON outbox(processed_at, outbox_id);
CREATE INDEX idx_provider_availability_provider ON provider_availability(provider_id);
CREATE INDEX idx_availability_exceptions_provider_date ON availability_exceptions(provider_id, exception_date);
CREATE INDEX idx_appointments_user ON appointments(user_id);
CREATE INDEX idx_appointments_provider_start ON appointments(provider_id, start_time);

-- ============================================================
-- SEED DATA  (roles are NOT seeded here — Better Auth admin plugin owns user.role)
-- ============================================================

INSERT INTO scoring_weights
    (skin_condition_weight, lifestyle_weight, sleep_quality_weight,
     routine_adherence_weight, hydration_weight, is_active)
VALUES (0.35, 0.20, 0.15, 0.20, 0.10, TRUE);

INSERT INTO ingredient_safety_config
    (avoid_deduction, caution_deduction, allergy_deduction, safe_threshold, warning_threshold, is_active)
VALUES (40.0, 15.0, 50.0, 80.0, 50.0, TRUE);

INSERT INTO recommendation_weights (concern_weight, skin_type_fit_weight, rating_weight, is_active)
VALUES (0.50, 0.35, 0.15, TRUE);

INSERT INTO skin_types (skin_type_name, description) VALUES
    ('Normal', 'Balanced oil and hydration'),
    ('Dry', 'Low sebum, prone to flaking'),
    ('Oily', 'Excess sebum production'),
    ('Combination', 'Oily T-zone, dry cheeks'),
    ('Sensitive', 'Reacts easily to products and environment');

INSERT INTO skin_concerns (concern_name, category) VALUES
    ('Acne', 'Blemish'),
    ('Hyperpigmentation', 'Tone'),
    ('Dark Spots', 'Tone'),
    ('Dry Skin', 'Hydration'),
    ('Oily Skin', 'Sebum'),
    ('Sensitive Skin', 'Sensitivity'),
    ('Wrinkles', 'Aging'),
    ('Fine Lines', 'Aging'),
    ('Redness', 'Sensitivity'),
    ('Uneven Skin Tone', 'Tone');
