[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[phases.build]
cmds = [
  "VITE_API_URL=https://miracle-production-e7d3.up.railway.app/api/v1 npm run build"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app"