"""Milestone 2 API — /api/v1/assessment/* and /api/v1/routine/*

Every route is protected by the Milestone 1 JWT layer (`require(...)`), reuses the
Milestone 1 session, audit and notification helpers, and adds no new auth of its own.
"""
from __future__ import annotations

import json
from datetime import date

from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy import desc, select
from sqlalchemy.orm import Session

from ..database import get_db
from ..deps import audit, notify, require
from ..models import (LifestyleLog, ProgressEntry, SkinAssessment, SkinProfile,
                      SkincareRoutine, User)
from ..schemas import (AssessmentIn, AssessmentOut, RoutineGenerateIn, RoutineLogOut,
                       RoutinePlanOut, RoutineStepOut, StepCompletionIn)
from ..services import assessment_engine, routine_engine, routine_logs, scoring_engine

router = APIRouter(prefix="/v1", tags=["milestone-2"])

DAILY_PHASES = ("AM", "PM")   # what counts toward daily compliance


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def _latest_lifestyle(db: Session, user_id: int) -> LifestyleLog | None:
    return db.scalar(select(LifestyleLog).where(LifestyleLog.user_id == user_id)
                     .order_by(desc(LifestyleLog.log_date)).limit(1))


def _expected_daily_steps(db: Session, user_id: int) -> int:
    """How many AM+PM steps the user's active routine expects each day."""
    return len(db.scalars(select(SkincareRoutine).where(
        SkincareRoutine.user_id == user_id,
        SkincareRoutine.is_active.is_(True),
        SkincareRoutine.time_of_day.in_(DAILY_PHASES),
    )).all())


def _run_engines(db: Session, user: User, data: dict) -> tuple[list[dict], dict, list[str]]:
    """Assessment -> scoring -> recommendations. The heart of Milestone 2."""
    concerns = assessment_engine.identify_skin_concerns(data)

    expected = _expected_daily_steps(db, user.id)
    completed, expected_total = routine_logs.consistency_last_7_days(db, user.id, expected)

    breakdown = scoring_engine.score_breakdown(
        concerns=concerns,
        sleep_hours=data.get("sleep_hours"),
        water_intake_l=data.get("water_intake_l"),
        completed_steps=completed,
        expected_steps=expected_total,
        environment_exposure=data.get("environment_exposure"),
        uses_sunscreen=data.get("uses_sunscreen", True),
        exercise_minutes=data.get("exercise_minutes"),
        stress_level=data.get("stress_level"),
        smokes=data.get("smokes", False),
    )

    recommendations = assessment_engine.generate_recommendations(
        concerns=concerns,
        skin_type=data.get("skin_type"),
        breakdown=breakdown,
        sleep_hours=data.get("sleep_hours"),
        water_intake_l=data.get("water_intake_l"),
        consistency=breakdown["breakdown"]["consistency"]["score"],
    )
    return concerns, breakdown, recommendations


def _persist_assessment(db: Session, user: User, data: dict, concerns: list[dict],
                        breakdown: dict, recommendations: list[str]) -> SkinAssessment:
    """Write the historical snapshot into skin_assessments (spec Step 3.2)."""
    b = breakdown["breakdown"]
    row = SkinAssessment(
        user_id=user.id,
        overall_score=breakdown["overall_score"],
        condition_score=b["skin_condition"]["score"],
        lifestyle_score=b["lifestyle"]["score"],
        consistency_score=b["consistency"]["score"],
        sleep_score=b["sleep"]["score"],
        hydration_score=b["hydration"]["score"],
        detected_concerns=json.dumps(concerns),
        primary_concern=assessment_engine.primary_concern(concerns),
        skin_type=data.get("skin_type"),
        recommendations=json.dumps(recommendations),
    )
    db.add(row)
    db.flush()

    # Feed the Milestone 1 progress chart so the two systems stay in step.
    db.add(ProgressEntry(
        user_id=user.id,
        entry_date=date.today(),
        skin_score=int(round(breakdown["overall_score"])),
        hydration=int(round(b["hydration"]["score"])),
        notes="Auto-generated by the Milestone 2 assessment engine",
    ))
    return row


def _save_routine(db: Session, user: User, assessment: SkinAssessment,
                  plan: dict[str, list[dict]]) -> None:
    """Replace the user's active plan with the newly generated one."""
    for old in db.scalars(select(SkincareRoutine).where(
            SkincareRoutine.user_id == user.id,
            SkincareRoutine.is_active.is_(True))).all():
        old.is_active = False

    for phase, steps in plan.items():
        for s in steps:
            db.add(SkincareRoutine(
                user_id=user.id,
                assessment_id=assessment.id,
                time_of_day=phase,
                step_number=s["step_number"],
                step_category=s["step_category"],
                instruction=s.get("instruction"),
                is_active=True,
            ))


def _assessment_out(row: SkinAssessment, storage: str = "") -> AssessmentOut:
    """Build the response.

    Constructed field-by-field rather than via model_validate, because the ORM
    stores `detected_concerns` / `recommendations` as JSON *strings* — they must
    be parsed into real lists before Pydantic sees them.
    """
    return AssessmentOut(
        id=row.id,
        user_id=row.user_id,
        overall_score=row.overall_score,
        band=scoring_engine.score_band(row.overall_score),
        skin_type=row.skin_type,
        primary_concern=row.primary_concern,
        detected_concerns=json.loads(row.detected_concerns or "[]"),
        recommendations=json.loads(row.recommendations or "[]"),
        created_at=row.created_at,
        consistency_source=storage,
        breakdown={
            "skin_condition": {"score": row.condition_score, "weight": scoring_engine.W_CONDITION,
                               "contribution": round(row.condition_score * scoring_engine.W_CONDITION, 2)},
            "lifestyle": {"score": row.lifestyle_score, "weight": scoring_engine.W_LIFESTYLE,
                          "contribution": round(row.lifestyle_score * scoring_engine.W_LIFESTYLE, 2)},
            "sleep": {"score": row.sleep_score, "weight": scoring_engine.W_SLEEP,
                      "contribution": round(row.sleep_score * scoring_engine.W_SLEEP, 2)},
            "consistency": {"score": row.consistency_score, "weight": scoring_engine.W_CONSISTENCY,
                            "contribution": round(row.consistency_score * scoring_engine.W_CONSISTENCY, 2)},
            "hydration": {"score": row.hydration_score, "weight": scoring_engine.W_HYDRATION,
                          "contribution": round(row.hydration_score * scoring_engine.W_HYDRATION, 2)},
        },
    )


# ---------------------------------------------------------------------------
# POST /api/v1/assessment/evaluate      (spec Step 2.1)
# ---------------------------------------------------------------------------
@router.post("/assessment/evaluate", response_model=AssessmentOut, status_code=201)
def evaluate(body: AssessmentIn, request: Request,
             user: User = Depends(require("assessment.create")),
             db: Session = Depends(get_db)):
    """Run the assessment + scoring engines, persist a snapshot, build the routine."""
    data = body.model_dump()
    supplied = {k: v for k, v in data.items() if v not in (None, "", {}, [])}

    # Fill any gap in the wizard payload from the stored Milestone 1 profile, so an
    # assessment is never penalised for data the user has already given us.
    profile = db.scalar(select(SkinProfile).where(SkinProfile.user_id == user.id))
    if profile:
        for field in ("age", "gender", "skin_type", "concerns", "sensitivities", "allergies"):
            if not data.get(field):
                data[field] = getattr(profile, field, None)

    latest = _latest_lifestyle(db, user.id)
    if latest:
        for field in ("sleep_hours", "water_intake_l", "exercise_minutes",
                      "stress_level", "environment_exposure"):
            if data.get(field) is None:
                data[field] = getattr(latest, field, None)

    concerns, breakdown, recommendations = _run_engines(db, user, data)
    assessment = _persist_assessment(db, user, data, concerns, breakdown, recommendations)

    # Keep the Milestone 1 skin profile in step with what the wizard collected.
    if profile:
        for field in ("age", "gender", "skin_type", "concerns", "sensitivities", "allergies"):
            if supplied.get(field):
                setattr(profile, field, supplied[field])

    # Persist today's lifestyle numbers into Milestone 1's own table too.
    if any(data.get(f) is not None for f in ("sleep_hours", "water_intake_l")):
        today_log = db.scalar(select(LifestyleLog).where(
            LifestyleLog.user_id == user.id, LifestyleLog.log_date == date.today()))
        if not today_log:
            today_log = LifestyleLog(user_id=user.id, log_date=date.today())
            db.add(today_log)
        for field in ("sleep_hours", "water_intake_l", "exercise_minutes",
                      "stress_level", "environment_exposure"):
            if data.get(field) is not None:
                setattr(today_log, field, data[field])

    if body.generate_routine:
        plan = routine_engine.generate_routine(
            skin_type=data.get("skin_type"),
            concerns=concerns,
            sensitivities=data.get("sensitivities"),
            db=db,
        )
        _save_routine(db, user, assessment, plan)

    notify(db, user.id, "Skin assessment complete",
           f"Your Skin Health Score is {breakdown['overall_score']} "
           f"({scoring_engine.score_band(breakdown['overall_score'])}).", "routine")
    audit(db, request, user, "assessment.evaluate", "skin_assessment", assessment.id,
          new_value={"score": breakdown["overall_score"],
                     "primary_concern": assessment.primary_concern})
    db.commit()
    db.refresh(assessment)
    return _assessment_out(assessment, routine_logs.storage_backend())


# ---------------------------------------------------------------------------
# GET /api/v1/assessment/score          (spec Step 3.2)
# ---------------------------------------------------------------------------
@router.get("/assessment/score", response_model=AssessmentOut)
def latest_score(recalculate: bool = False, request: Request = None,
                 user: User = Depends(require("assessment.read_own")),
                 db: Session = Depends(get_db)):
    """The user's latest score breakdown.

    `?recalculate=true` re-runs the engine against current data (so today's
    checklist ticks are reflected) and saves a fresh historical snapshot.
    """
    if not recalculate:
        row = db.scalar(select(SkinAssessment)
                        .where(SkinAssessment.user_id == user.id)
                        .order_by(desc(SkinAssessment.created_at)).limit(1))
        if row:
            return _assessment_out(row, routine_logs.storage_backend())

    # No assessment yet (or a recalculation was requested): build one from
    # whatever Milestone 1 data we already hold.
    profile = db.scalar(select(SkinProfile).where(SkinProfile.user_id == user.id))
    latest = _latest_lifestyle(db, user.id)
    if not profile and not latest:
        raise HTTPException(status.HTTP_404_NOT_FOUND,
                            "No assessment yet — complete the skin assessment to get your score.")

    data = {
        "age": getattr(profile, "age", None),
        "skin_type": getattr(profile, "skin_type", None),
        "concerns": getattr(profile, "concerns", None),
        "sensitivities": getattr(profile, "sensitivities", None),
        "sleep_hours": getattr(latest, "sleep_hours", None),
        "water_intake_l": getattr(latest, "water_intake_l", None),
        "exercise_minutes": getattr(latest, "exercise_minutes", None),
        "stress_level": getattr(latest, "stress_level", None),
        "environment_exposure": getattr(latest, "environment_exposure", None),
    }
    concerns, breakdown, recommendations = _run_engines(db, user, data)
    assessment = _persist_assessment(db, user, data, concerns, breakdown, recommendations)
    audit(db, request, user, "assessment.score", "skin_assessment", assessment.id,
          new_value={"score": breakdown["overall_score"], "recalculated": recalculate})
    db.commit()
    db.refresh(assessment)
    return _assessment_out(assessment, routine_logs.storage_backend())


@router.get("/assessment/history", response_model=list[AssessmentOut])
def history(limit: int = 30,
            user: User = Depends(require("assessment.read_own")),
            db: Session = Depends(get_db)):
    """Every historical snapshot — powers the progress chart."""
    rows = db.scalars(select(SkinAssessment)
                      .where(SkinAssessment.user_id == user.id)
                      .order_by(desc(SkinAssessment.created_at))
                      .limit(min(limit, 200))).all()
    return [_assessment_out(r) for r in rows]


# ---------------------------------------------------------------------------
# POST /api/v1/routine/generate         (spec Step 4.1)
# ---------------------------------------------------------------------------
@router.post("/routine/generate", response_model=RoutinePlanOut, status_code=201)
def generate(body: RoutineGenerateIn, request: Request,
             user: User = Depends(require("routine.generate")),
             db: Session = Depends(get_db)):
    """(Re)generate the AM/PM/Weekly/Seasonal plan from the latest assessment."""
    assessment = db.scalar(select(SkinAssessment)
                           .where(SkinAssessment.user_id == user.id)
                           .order_by(desc(SkinAssessment.created_at)).limit(1))
    if not assessment:
        raise HTTPException(status.HTTP_400_BAD_REQUEST,
                            "Run an assessment first — the routine is built from its results.")

    profile = db.scalar(select(SkinProfile).where(SkinProfile.user_id == user.id))
    concerns = json.loads(assessment.detected_concerns or "[]")
    skin_type = body.skin_type or assessment.skin_type or getattr(profile, "skin_type", None)

    plan = routine_engine.generate_routine(
        skin_type=skin_type,
        concerns=concerns,
        sensitivities=getattr(profile, "sensitivities", None),
        db=db,
    )
    _save_routine(db, user, assessment, plan)
    audit(db, request, user, "routine.generate", "skincare_routine", assessment.id,
          new_value={"skin_type": skin_type, "steps": sum(len(v) for v in plan.values())})
    db.commit()
    return _routine_plan(db, user)


# ---------------------------------------------------------------------------
# GET /api/v1/routine                   (spec Step 5.2)
# ---------------------------------------------------------------------------
@router.get("/routine", response_model=RoutinePlanOut)
def get_routine(user: User = Depends(require("routine.read_own")),
                db: Session = Depends(get_db)):
    """The active plan, with today's completion state merged in from routine_logs."""
    return _routine_plan(db, user)


def _routine_plan(db: Session, user: User) -> RoutinePlanOut:
    rows = db.scalars(select(SkincareRoutine).where(
        SkincareRoutine.user_id == user.id,
        SkincareRoutine.is_active.is_(True),
    ).order_by(SkincareRoutine.time_of_day, SkincareRoutine.step_number)).all()

    today_log = routine_logs.get_log(db, user.id, date.today())
    done_ids = {s["routine_step_id"] for s in today_log.get("completed_steps", [])}

    plan = RoutinePlanOut()
    if rows:
        plan.assessment_id = rows[0].assessment_id
        plan.generated_at = rows[0].created_at

    daily_total = 0
    daily_done = 0
    for r in rows:
        step = RoutineStepOut.model_validate(r)
        step.completed = r.id in done_ids
        getattr(plan, r.time_of_day).append(step)
        if r.time_of_day in DAILY_PHASES:
            daily_total += 1
            daily_done += 1 if step.completed else 0

    plan.total_daily_steps = daily_total
    plan.completed_today = daily_done
    plan.completion_percent = round((daily_done / daily_total) * 100, 1) if daily_total else 0.0
    return plan


# ---------------------------------------------------------------------------
# POST /api/v1/routine/complete         (spec Step 5.2 — the checkbox)
# ---------------------------------------------------------------------------
@router.post("/routine/complete", response_model=RoutinePlanOut)
def complete_step(body: StepCompletionIn,
                  user: User = Depends(require("routine.log_own")),
                  db: Session = Depends(get_db)):
    """Tick or untick one routine step — writes straight into routine_logs."""
    step = db.get(SkincareRoutine, body.routine_step_id)
    if not step or step.user_id != user.id:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Routine step not found")

    log_date = body.log_date or date.today()
    if log_date > date.today():
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Cannot log a step for a future date")

    routine_logs.toggle_step(db, user.id, log_date, body.routine_step_id, body.completed)
    return _routine_plan(db, user)


@router.get("/routine/log", response_model=RoutineLogOut)
def get_routine_log(on: date | None = None,
                    user: User = Depends(require("routine.read_own")),
                    db: Session = Depends(get_db)):
    """The raw routine_logs document for a day — shows exactly what is stored."""
    doc = routine_logs.get_log(db, user.id, on or date.today())
    doc["storage"] = routine_logs.storage_backend()
    return doc


@router.post("/routine/log/metrics", response_model=RoutineLogOut)
def log_metrics(water_intake_ml: int | None = None, sleep_hours: float | None = None,
                user: User = Depends(require("routine.log_own")),
                db: Session = Depends(get_db)):
    """Record today's water and sleep into the same routine_logs document."""
    doc = routine_logs.update_metrics(db, user.id, date.today(),
                                      water_intake_ml, sleep_hours)
    doc["storage"] = routine_logs.storage_backend()
    return doc
