# Placeholder catalog until Milestone 3's real product scraping lands.
# Every ingredient here comes from the "Ingredient Categories" list in the
# Milestone 2 spec image, so this doubles as a first pass at Ingredient
# Intelligence data until that module gets built properly.

SEED_PRODUCTS = [
    {
        "name": "Gentle Foaming Cleanser",
        "brand": "CeraVe",
        "category": "Cleansing",
        "price_usd": 14.99,
        "rating": 4.6,
        "skin_types": ["Oily", "Combination"],
        "target_concerns": ["Acne", "Oily Skin"],
        "key_ingredients": ["Ceramides", "Niacinamide"],
        "avoid_for_allergies": [],
        "description": "Foaming daily cleanser for oily and combination skin.",
    },
    {
        "name": "Hydrating Cream Cleanser",
        "brand": "CeraVe",
        "category": "Cleansing",
        "price_usd": 15.99,
        "rating": 4.7,
        "skin_types": ["Dry Skin", "Sensitive Skin", "All"],
        "target_concerns": ["Dry Skin", "Redness", "Sensitive Skin"],
        "key_ingredients": ["Ceramides", "Hyaluronic Acid"],
        "avoid_for_allergies": ["Fragrance"],
        "description": "Non-foaming cleanser that preserves the skin barrier.",
    },
    {
        "name": "2% Salicylic Acid Treatment",
        "brand": "Paula's Choice",
        "category": "Treatment",
        "price_usd": 32.00,
        "rating": 4.5,
        "skin_types": ["Oily", "Combination"],
        "target_concerns": ["Acne", "Oily Skin", "Uneven Skin Tone"],
        "key_ingredients": ["Salicylic Acid", "AHAs/BHA"],
        "avoid_for_allergies": [],
        "description": "Leave-on BHA exfoliant for breakouts and clogged pores.",
    },
    {
        "name": "10% Niacinamide + Zinc Serum",
        "brand": "The Ordinary",
        "category": "Treatment",
        "price_usd": 6.50,
        "rating": 4.4,
        "skin_types": ["Oily", "Combination", "All"],
        "target_concerns": ["Acne", "Oily Skin", "Hyperpigmentation", "Dark Spots"],
        "key_ingredients": ["Niacinamide"],
        "avoid_for_allergies": [],
        "description": "Oil-control serum that also helps with tone evenness.",
    },
    {
        "name": "Vitamin C Brightening Serum",
        "brand": "SkinIntel Labs",
        "category": "Treatment",
        "price_usd": 28.00,
        "rating": 4.5,
        "skin_types": ["All"],
        "target_concerns": ["Hyperpigmentation", "Dark Spots", "Uneven Skin Tone", "Fine Lines"],
        "key_ingredients": ["Vitamin C"],
        "avoid_for_allergies": [],
        "description": "Antioxidant serum for brightening and early sun-damage repair.",
    },
    {
        "name": "0.3% Retinol Night Serum",
        "brand": "SkinIntel Labs",
        "category": "Night Care",
        "price_usd": 24.00,
        "rating": 4.3,
        "skin_types": ["Combination", "Dry Skin"],
        "target_concerns": ["Wrinkles", "Fine Lines", "Uneven Skin Tone"],
        "key_ingredients": ["Retinoids", "Peptides"],
        "avoid_for_allergies": [],
        "description": "Nightly retinoid for fine lines and texture — start slow.",
    },
    {
        "name": "Hyaluronic Acid Hydrating Serum",
        "brand": "SkinIntel Labs",
        "category": "Moisturizing",
        "price_usd": 19.00,
        "rating": 4.7,
        "skin_types": ["All"],
        "target_concerns": ["Dry Skin", "Fine Lines"],
        "key_ingredients": ["Hyaluronic Acid", "Peptides"],
        "avoid_for_allergies": [],
        "description": "Lightweight humectant serum, layers under any moisturizer.",
    },
    {
        "name": "Barrier Repair Moisturizer",
        "brand": "CeraVe",
        "category": "Moisturizing",
        "price_usd": 18.99,
        "rating": 4.8,
        "skin_types": ["Sensitive Skin", "Dry Skin", "All"],
        "target_concerns": ["Redness", "Sensitive Skin", "Dry Skin"],
        "key_ingredients": ["Ceramides"],
        "avoid_for_allergies": ["Fragrance"],
        "description": "Fragrance-free moisturizer for reactive or dry skin.",
    },
    {
        "name": "Oil-Free Gel Moisturizer",
        "brand": "Neutrogena",
        "category": "Moisturizing",
        "price_usd": 12.99,
        "rating": 4.3,
        "skin_types": ["Oily", "Combination"],
        "target_concerns": ["Oily Skin", "Acne"],
        "key_ingredients": ["Hyaluronic Acid"],
        "avoid_for_allergies": [],
        "description": "Lightweight gel moisturizer that won't clog pores.",
    },
    {
        "name": "Mineral SPF 50 Sunscreen",
        "brand": "La Roche-Posay",
        "category": "Sun Protection",
        "price_usd": 28.99,
        "rating": 4.6,
        "skin_types": ["All"],
        "target_concerns": ["Hyperpigmentation", "Dark Spots", "Wrinkles", "Sensitive Skin"],
        "key_ingredients": [],
        "avoid_for_allergies": ["Parabens"],
        "description": "Broad-spectrum mineral sunscreen, safe for daily use under makeup.",
    },
    {
        "name": "Tinted SPF 30 for Oily Skin",
        "brand": "EltaMD",
        "category": "Sun Protection",
        "price_usd": 39.00,
        "rating": 4.7,
        "skin_types": ["Oily", "Combination"],
        "target_concerns": ["Acne", "Oily Skin", "Hyperpigmentation"],
        "key_ingredients": ["Niacinamide"],
        "avoid_for_allergies": ["Parabens"],
        "description": "Matte-finish sunscreen formulated for acne-prone skin.",
    },
    {
        "name": "Weekly AHA/BHA Exfoliating Peel",
        "brand": "SkinIntel Labs",
        "category": "Exfoliation",
        "price_usd": 22.00,
        "rating": 4.2,
        "skin_types": ["Oily", "Combination"],
        "target_concerns": ["Dark Spots", "Uneven Skin Tone", "Wrinkles"],
        "key_ingredients": ["AHAs/BHA"],
        "avoid_for_allergies": [],
        "description": "Weekly exfoliating treatment for tone and texture.",
    },
    {
        "name": "Gentle Enzyme Exfoliator",
        "brand": "SkinIntel Labs",
        "category": "Exfoliation",
        "price_usd": 20.00,
        "rating": 4.4,
        "skin_types": ["Sensitive Skin", "Dry Skin", "All"],
        "target_concerns": ["Sensitive Skin", "Dry Skin", "Redness"],
        "key_ingredients": ["Ceramides"],
        "avoid_for_allergies": ["Fragrance"],
        "description": "Low-irritation exfoliant safe for sensitive and reactive skin.",
    },
]
