import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ArrowUpRight, Clock, X, Sparkles } from 'lucide-react';
import { ImageWithFallback } from '../../figma/ImageWithFallback';
import { Section, Reveal, Eyebrow } from '../primitives';
import { IMG } from '../../../data/images';
import { useApp } from '../../../store/AppState';

export interface JournalArticle {
  title: string;
  cat: string;
  read: string;
  img: string;
  by: string;
  accent: string;
  lede: string;
  sections: { h: string; p: string }[];
  tags: string[];
}

export const JOURNAL_ARTICLES: JournalArticle[] = [
  {
    title: 'Building a Morning Skincare Routine',
    cat: 'Routine',
    read: '6 min',
    img: IMG.ritual,
    by: 'Dr. Lena Ford',
    accent: '#7bab5a',
    lede: 'A luminous complexion is built before breakfast. The morning is when your skin faces its harshest tests — UV light, pollution, blue light and friction — so a considered AM routine is less about pampering and more about protection. Done well, it takes under four minutes and pays dividends for decades.',
    sections: [
      { h: 'Start with a gentle cleanse', p: 'Through the night your skin sheds dead cells, secretes sebum and processes whatever you applied before bed. Rinsing with a low-pH gel cleanser — ideally between 4.5 and 5.5 — lifts that residue without stripping the acid mantle that keeps your barrier resilient. If your skin feels tight or squeaky afterwards, your cleanser is too harsh: that tightness is dehydration, not cleanliness. On mornings when skin feels balanced, even a splash of lukewarm water is enough to prep the canvas.' },
      { h: 'Antioxidants come first', p: 'The single most valuable morning active is a stabilised antioxidant serum. Vitamin C (L-ascorbic acid at 10–15%) neutralises the free radicals generated by daylight and city pollution before they can degrade collagen and trigger dark spots. Applied to slightly damp skin, it also lays down a brightening base that makes every subsequent step more effective. Give it 30–60 seconds to absorb before moving on.' },
      { h: 'Lock in hydration', p: 'Next, bind water into the skin with a humectant layer — hyaluronic acid holds up to a thousand times its weight in moisture and plumps fine lines within minutes. Seal it with a lightweight moisturiser containing ceramides so the water you just added cannot evaporate away through the day. Combination and oily skin still need this step; skipping moisturiser only pushes the skin to overproduce oil.' },
      { h: 'Never, ever skip SPF', p: 'Dermatologists agree that up to 80% of visible facial ageing is driven by ultraviolet exposure. A broad-spectrum mineral SPF50 is, without exaggeration, the most powerful anti-ageing product you will ever own — more impactful than any serum. Apply two finger-lengths to the face and neck as the final morning step, and reapply every two hours if you are outdoors or near windows.' },
      { h: 'Consistency is the real secret', p: 'A simple routine performed every single morning will always outperform an elaborate one you abandon after a fortnight. Anchor these four steps to an existing habit — brushing your teeth, making coffee — so they become automatic. Skin rewards rhythm, and the compounding effect of daily protection is visible within a single season.' },
    ],
    tags: ['Morning', 'Vitamin C', 'SPF', 'Barrier', 'Hydration'],
  },
  {
    title: 'Why Vitamin C Belongs in Your AM Routine',
    cat: 'Ingredients',
    read: '5 min',
    img: IMG.serumAmber,
    by: 'Aria Mehta',
    accent: '#e7c65a',
    lede: 'Vitamin C is the most decorated brightening ingredient in skincare — but its reputation is only deserved when the formula is stabilised, correctly dosed and layered with intention. Here is how to turn a good serum into visible, lasting radiance.',
    sections: [
      { h: 'What it actually does', p: 'Pure L-ascorbic acid works on three fronts at once: it interrupts melanin overproduction to fade dark spots and post-blemish marks, it is an essential cofactor in collagen synthesis so skin looks firmer over time, and it is a potent antioxidant that defends against daily environmental damage. Unlike an exfoliant, its results are cumulative — most people notice a brighter, more even tone somewhere between weeks eight and twelve of consistent use.' },
      { h: 'Concentration and stability', p: 'The effective range sits between 10% and 20%; below that you see little benefit, and above it irritation rises without any extra reward. Just as important is stability — Vitamin C oxidises when exposed to light and air, turning yellow-brown and losing potency. Our serum is buffered at 15% and sealed in opaque, air-restrictive packaging so the last drop is as active as the first. If your serum has darkened, it is telling you it has expired.' },
      { h: 'The partners it loves', p: 'Vitamin C performs best in the company of Vitamin E and ferulic acid, which stabilise it and extend its antioxidant reach. It also sits beautifully under sunscreen, effectively doubling your daytime defence. Introduce it slowly — every other morning for the first week — if your skin is sensitive, and always follow with SPF, since freshly brightened skin is more precious to protect.' },
      { h: 'Common mistakes to avoid', p: 'Do not layer strong Vitamin C directly with high-strength niacinamide or exfoliating acids in the same step, as it can cause fleeting flushing and blunt the benefits. Store the bottle away from a sunny windowsill, keep the cap sealed, and resist the urge to double the dose — more product does not mean more results, only more irritation.' },
    ],
    tags: ['Vitamin C', 'Brightening', 'Antioxidant', 'Even tone'],
  },
  {
    title: "A Beginner's Guide to Retinol",
    cat: 'Education',
    read: '8 min',
    img: IMG.serumSand,
    by: 'Dr. Lena Ford',
    accent: '#c3a468',
    lede: 'Retinol is the most rigorously studied anti-ageing molecule in dermatology — and also the most misused. Handled patiently it smooths texture, softens lines and clears congestion; rushed, it delivers weeks of redness and flaking that make most people quit. This is how to start and actually stick with it.',
    sections: [
      { h: 'How retinol works', p: 'Retinol is a form of Vitamin A that, once converted in the skin, accelerates cell turnover and signals fibroblasts to produce fresh collagen. The result over months is smoother texture, faded pigmentation, refined pores and softened fine lines. Because it is speeding up processes that normally slow with age, the early adjustment period — sometimes called retinisation — is temporary, not a sign the product is wrong for you.' },
      { h: 'Go low and slow', p: 'Begin with a low-strength, encapsulated formula just two nights a week. Encapsulation releases the active gradually, dramatically reducing irritation while preserving results. Hold that frequency for two to four weeks, and only increase to every other night once your skin tolerates it comfortably. There is no prize for rushing — the skin that adapts slowly is the skin that keeps its glow.' },
      { h: 'The sandwich method', p: 'For reactive or dry skin, apply a thin layer of moisturiser first, then your retinol, then moisturiser again. This "sandwich" buffers delivery so the active works without overwhelming the barrier. Always use retinol at night — it is deactivated by sunlight — and never combine it in the same routine with strong acids or Vitamin C, which belong in your morning.' },
      { h: 'Protect and be patient', p: 'Retinol makes skin more photosensitive, so daily SPF is non-negotiable while you use it. Expect some dryness in the first fortnight; ride it out with extra moisturiser rather than stopping. Meaningful change — visibly smoother texture and softened lines — typically appears around week eight and deepens over six months of consistent use.' },
      { h: 'Who should wait', p: 'Retinol is not for everyone right now. If you are pregnant or breastfeeding, dermatologists advise pausing retinoids entirely and leaning on gentler alternatives like bakuchiol or peptides. If your barrier is currently compromised — stinging, flaking, inflamed — repair it first, then introduce retinol onto healthy skin.' },
    ],
    tags: ['Retinol', 'Anti-ageing', 'Night', 'Collagen'],
  },
  {
    title: 'Understanding Niacinamide',
    cat: 'Ingredients',
    read: '4 min',
    img: IMG.serumClear,
    by: 'Aria Mehta',
    accent: '#7fa8c9',
    lede: "Niacinamide is the quiet overachiever of the ingredient world: it calms redness, refines pores, controls shine and reinforces the barrier, all while playing nicely with almost every other active. If you only add one supporting serum to your routine, this is the one.",
    sections: [
      { h: 'A genuine all-rounder', p: 'A form of Vitamin B3, niacinamide regulates sebum, visibly tightens the look of enlarged pores, fades uneven tone and — crucially — boosts the skin\'s production of ceramides, the lipids that hold the barrier together. At a 10% concentration it delivers these benefits while remaining gentle enough for daily, twice-daily use across nearly every skin type.' },
      { h: 'Ideal for oily and combination skin', p: 'By moderating oil production without stripping, niacinamide reduces midday shine and the congestion that leads to breakouts — making it a favourite for the T-zone in combination skin. Because it strengthens rather than dries, it manages oil without triggering the rebound greasiness that harsh mattifying products cause.' },
      { h: 'How to layer it', p: 'Apply niacinamide to clean skin before your heavier creams, morning or night. It is famously easy-going, sitting happily alongside hyaluronic acid, peptides, retinol and moisturisers. The old warning about not mixing it with Vitamin C has been largely debunked for modern formulas — but if your skin is very sensitive, simply use them at opposite ends of the day.' },
      { h: 'What to expect', p: 'Niacinamide is a slow, steady worker rather than an overnight sensation. Oil control and a calmer, less red complexion often show within two to three weeks, while pore refinement and tone improvements build over a couple of months. Its reliability and near-universal tolerance are exactly why it appears in so many well-designed routines.' },
    ],
    tags: ['Niacinamide', 'Pores', 'Redness', 'Oil control'],
  },
  {
    title: 'How to Layer Your Skincare',
    cat: 'Routine',
    read: '7 min',
    img: IMG.trioJars,
    by: 'Dr. Lena Ford',
    accent: '#2f6b4c',
    lede: '"Thinnest to thickest" is the advice everyone repeats — and it is only half the story. The right order is what lets each active reach the skin, do its job and coexist with the others. Here is a clear framework for both morning and night.',
    sections: [
      { h: 'The golden rule of order', p: 'Work from the most water-light textures to the richest: cleanse, then tone or essence, then treatment serums, then eye cream, then moisturiser, and finally any occlusive balm or — in the morning — sunscreen. Thin, water-based formulas cannot penetrate through heavy creams, so applying them first ensures their actives actually reach living skin rather than sitting uselessly on the surface.' },
      { h: 'Separate the actives that clash', p: 'Some powerhouse ingredients simply work better apart. Reserve Vitamin C and exfoliating acids for the morning, and keep retinol for the night. This rhythm prevents irritation, protects each molecule\'s stability, and lets you enjoy the full benefit of both without the redness that comes from cramming everything into one sitting.' },
      { h: 'Give each layer a moment', p: 'Pause 30 to 60 seconds between steps so each layer absorbs before the next goes on. This small patience prevents pilling — those little rolls of product — and keeps the whole routine feeling weightless. A useful cue: a layer is ready for the next when the skin feels touch-dry rather than slick.' },
      { h: 'Match the routine to the goal', p: 'Mornings are about protection: antioxidants, hydration and SPF. Nights are about repair: this is when retinol, richer moisturisers and reparative peptides do their best work, since skin regenerates most actively while you sleep. You do not need a dozen steps — a focused four or five, correctly ordered, will always beat a crowded shelf.' },
      { h: 'Let your skin lead', p: 'Treat this framework as a foundation, not a rulebook. On a day when skin feels irritated, strip back to cleanse-moisturise-SPF and let it recover. Introduce only one new active at a time so you can tell what is working, and adjust with the seasons — lighter in humid summer, richer in dry winter.' },
    ],
    tags: ['Layering', 'AM & PM', 'Routine', 'Actives'],
  },
];

export function Journal() {
  const [activeArticle, setActiveArticle] = useState<JournalArticle | null>(null);
  const { setQuizOpen } = useApp();
  const feature = JOURNAL_ARTICLES[0];
  const rest = JOURNAL_ARTICLES.slice(1);

  return (
    <>
      <Section id="journal" style={{ background: 'var(--sec-forest)', color: 'var(--forest-fg)', borderRadius: '48px' }}>
        <div className="mb-12 flex flex-wrap items-end justify-between gap-6">
          <div className="max-w-xl">
            <Eyebrow className="!text-[#9caf92]">The Journal</Eyebrow>
            <h2 className="mt-5 font-display" style={{ fontSize: 'clamp(2rem,4vw,3.4rem)', lineHeight: 1.05, fontWeight: 400, letterSpacing: '-0.02em' }}>
              Skincare, decoded
              <span className="italic text-[#c3a468]"> beautifully.</span>
            </h2>
          </div>
          <button
            onClick={() => setActiveArticle(feature)}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '8px',
              borderRadius: '999px', cursor: 'pointer',
              border: '1px solid rgba(246,241,230,0.3)', background: 'transparent',
              color: '#f6f1e6', padding: '13px 24px', fontFamily: 'inherit', fontSize: '0.9rem',
              transition: 'border-color .25s, color .25s',
            }}
            onMouseEnter={(e) => { e.currentTarget.style.borderColor = '#c3a468'; e.currentTarget.style.color = '#c3a468'; }}
            onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'rgba(246,241,230,0.3)'; e.currentTarget.style.color = '#f6f1e6'; }}
          >
            Visit the Journal
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" style={{ width: '15px', height: '15px' }}>
              <path d="M7 17 17 7"/><path d="M7 7h10v10"/>
            </svg>
          </button>
        </div>

        <div className="grid gap-6 lg:grid-cols-[1.2fr_1fr]">
          <Reveal>
            <motion.div
              whileHover={{ y: -6 }}
              onClick={() => setActiveArticle(feature)}
              className="group block h-full cursor-pointer overflow-hidden rounded-3xl border border-white/10"
            >
              <div className="relative min-h-[380px] h-full overflow-hidden">
                <ImageWithFallback src={feature.img} alt={feature.title} className="h-full w-full object-cover transition-transform duration-[900ms] group-hover:scale-105" />
                <div className="absolute inset-0" style={{ background: 'linear-gradient(180deg, transparent 40%, rgba(10,24,15,0.85))' }} />
                <div className="absolute bottom-0 left-0 right-0 p-7">
                  <span className="rounded-full bg-[#c3a468] px-3 py-1 font-body text-[0.65rem] uppercase tracking-widest text-[#16301f]">{feature.cat}</span>
                  <h3 className="mt-4 max-w-md font-display text-3xl leading-tight" style={{ fontWeight: 400 }}>{feature.title}</h3>
                  <div className="mt-3 flex items-center gap-2 font-body text-[0.8rem] text-[var(--cream)]/70">
                    <Clock className="h-3.5 w-3.5" /> {feature.read} read
                  </div>
                </div>
              </div>
            </motion.div>
          </Reveal>

          <div className="grid gap-4 sm:grid-cols-2">
            {rest.map((a, i) => (
              <Reveal key={a.title} delay={i * 0.05}>
                <motion.div
                  whileHover={{ y: -5 }}
                  onClick={() => setActiveArticle(a)}
                  className="group flex h-full cursor-pointer flex-col overflow-hidden rounded-2xl border border-white/10 bg-white/[0.04]"
                >
                  <div className="relative h-32 overflow-hidden">
                    <ImageWithFallback src={a.img} alt={a.title} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-110" />
                  </div>
                  <div className="flex flex-1 flex-col p-4">
                    <span className="font-body text-[0.62rem] uppercase tracking-widest text-[#9caf92]">{a.cat}</span>
                    <h4 className="mt-1.5 font-display text-[1.05rem] leading-snug" style={{ fontWeight: 400 }}>{a.title}</h4>
                    <div className="mt-auto flex items-center justify-between pt-3 font-body text-[0.75rem] text-[var(--cream)]/60">
                      <span>{a.read}</span>
                      <ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
                    </div>
                  </div>
                </motion.div>
              </Reveal>
            ))}
          </div>
        </div>
      </Section>

      {/* ARTICLE MODAL (1:1 with Miracle Landing.dc.html lines 658-695) */}
      <AnimatePresence>
        {activeArticle && (
          <div
            className="fixed inset-0 z-[90] flex items-start justify-center overflow-y-auto p-6 backdrop-blur-md"
            style={{ background: 'rgba(10,19,13,0.62)', animation: 'fadeDown 0.3s ease both' }}
            onClick={() => setActiveArticle(null)}
          >
            <motion.article
              initial={{ opacity: 0, scale: 0.94, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.94, y: 20 }}
              transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
              onClick={(e) => e.stopPropagation()}
              className="relative my-auto w-full max-w-[760px] overflow-hidden rounded-[28px] bg-card text-foreground shadow-[0_50px_120px_-40px_rgba(22,48,31,0.6)]"
            >
              <div className="relative h-[280px] overflow-hidden">
                <ImageWithFallback src={activeArticle.img} alt={activeArticle.title} className="h-full w-full object-cover" />
                <div className="absolute inset-0" style={{ background: 'linear-gradient(180deg, rgba(10,24,15,0.1) 30%, rgba(10,24,15,0.82))' }} />
                <button
                  onClick={() => setActiveArticle(null)}
                  aria-label="Close article"
                  className="absolute right-45 top-45 z-10 grid h-95 w-95 place-items-center rounded-full bg-white/85 text-[#16301f] shadow-md transition-transform hover:scale-108"
                  style={{ top: '18px', right: '18px', width: '38px', height: '38px' }}
                >
                  <X className="h-5 w-5" />
                </button>
                <div className="absolute bottom-0 left-0 right-0 p-7">
                  <span className="rounded-full bg-[#c3a468] px-3.5 py-1.5 font-body text-[0.66rem] uppercase tracking-[0.16em] text-[#16301f]">
                    {activeArticle.cat}
                  </span>
                  <h2 className="mt-4 max-w-xl font-display text-3xl text-[#f6f1e6]" style={{ fontWeight: 400, fontSize: 'clamp(1.6rem,3.2vw,2.4rem)', lineHeight: 1.12 }}>
                    {activeArticle.title}
                  </h2>
                  <div className="mt-3 flex items-center gap-3.5 font-body text-[0.8rem] text-[rgba(246,241,230,0.8)]">
                    <span className="flex items-center gap-1.5"><Clock className="h-3.5 w-3.5" /> {activeArticle.read} read</span>
                    <span className="flex items-center gap-1.5"><Sparkles className="h-3.5 w-3.5" /> {activeArticle.by}</span>
                  </div>
                </div>
              </div>

              <div className="p-8">
                <p className="font-display text-xl font-light leading-relaxed text-foreground" style={{ fontSize: '1.2rem', lineHeight: 1.5 }}>
                  {activeArticle.lede}
                </p>
                <div className="mt-6 flex flex-col gap-6">
                  {activeArticle.sections.map((sec, idx) => (
                    <div key={idx}>
                      <h3 className="mb-2 flex items-center gap-2.5 font-display text-lg text-foreground" style={{ fontWeight: 400 }}>
                        <span className="h-2 w-2 rounded-full" style={{ background: activeArticle.accent || '#2f6b4c' }} />
                        {sec.h}
                      </h3>
                      <p className="font-body text-[0.95rem] leading-relaxed text-muted-foreground">
                        {sec.p}
                      </p>
                    </div>
                  ))}
                </div>

                <div className="mt-7 flex flex-wrap gap-2">
                  {activeArticle.tags.map((t, idx) => (
                    <span key={idx} className="rounded-full border border-border bg-[rgba(156,175,146,0.12)] px-3.5 py-1.5 font-body text-[0.75rem] text-foreground">
                      {t}
                    </span>
                  ))}
                </div>

                <div className="mt-7 flex flex-wrap items-center justify-between gap-4 border-t border-border pt-6">
                  <div className="flex items-center gap-3">
                    <span className="grid h-11 w-11 place-items-center rounded-full bg-[#16301f] font-display text-base text-[#f6f1e6]">M</span>
                    <div>
                      <p className="font-body text-[0.9rem] font-medium text-foreground">{activeArticle.by}</p>
                      <p className="font-body text-[0.76rem] text-muted-foreground">Miracle Journal</p>
                    </div>
                  </div>
                  <button
                    onClick={() => {
                      setActiveArticle(null);
                      setQuizOpen(true);
                    }}
                    className="inline-flex items-center gap-2 rounded-full bg-[#16301f] px-6 py-3.5 font-body text-[0.9rem] text-[#f6f1e6] transition-transform hover:-translate-y-0.5 hover:shadow-lg"
                  >
                    Build my ritual <ArrowUpRight className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </motion.article>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}
