"""baseline user_profiles and skin_profile tables

Revision ID: 50e82a643bf9
Revises:
Create Date: 2026-07-08 19:14:26.399771

Hand-written, not autogenerated: the live database this was reconciled against already
had these tables (loaded directly from database_schemas/skinlytics_postgresql_schema_v3.sql,
confirmed with the user), so `alembic revision --autogenerate` produced an empty diff —
there was no second, empty database available to diff against for a "real" migration.
This file is written to exactly match app/services/{user,skin_profile}/models.py, which
were themselves verified against the live schema until the autogenerate diff was empty.
Applied here via `alembic stamp` (no DDL executed against the already-populated
database) — but `upgrade()` is real and will correctly create these tables on any other,
genuinely fresh database.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "50e82a643bf9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "skin_types",
        sa.Column("skin_type_id", sa.Integer(), primary_key=True),
        sa.Column("skin_type_name", sa.String(), nullable=True, unique=True),
        sa.Column("description", sa.Text(), nullable=True),
    )

    op.create_table(
        "skin_concerns",
        sa.Column("concern_id", sa.Integer(), primary_key=True),
        sa.Column("concern_name", sa.String(), nullable=True, unique=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
    )

    op.create_table(
        "user_profiles",
        sa.Column("profile_id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("user.id", ondelete="CASCADE")),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("profile_image_url", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()")),
        # Not in the documented v3 schema — schema drift, see models.py's docstring.
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True, server_default="user"),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")),
    )
    op.create_index("idx_user_profiles_user", "user_profiles", ["user_id"])
    op.create_unique_constraint("user_profiles_user_id_key", "user_profiles", ["user_id"])
    op.create_index("ix_user_profiles_email", "user_profiles", ["email"])
    op.create_index("user_profiles_email_key", "user_profiles", ["email"], unique=True)

    op.create_table(
        "skin_profiles",
        sa.Column("skin_profile_id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.String(), sa.ForeignKey("user.id", ondelete="CASCADE")),
        sa.Column(
            "skin_type_id",
            sa.Integer(),
            sa.ForeignKey("skin_types.skin_type_id"),
            nullable=False,
        ),
        sa.Column("age_group", sa.String(), nullable=True),
        sa.Column("allergies", sa.Text(), nullable=True),
        sa.Column("sensitivities", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true")),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false")),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()")),
    )
    op.create_index("idx_skin_profiles_user", "skin_profiles", ["user_id"])

    op.create_table(
        "skin_profile_concerns",
        sa.Column("profile_concern_id", sa.Integer(), primary_key=True),
        sa.Column(
            "skin_profile_id",
            sa.Integer(),
            sa.ForeignKey("skin_profiles.skin_profile_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "concern_id",
            sa.Integer(),
            sa.ForeignKey("skin_concerns.concern_id"),
            nullable=False,
        ),
        sa.Column("severity_rating", sa.Integer(), nullable=True),
        sa.Column("priority_level", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.CheckConstraint("severity_rating BETWEEN 1 AND 10", name="ck_concern_severity"),
        sa.CheckConstraint("priority_level BETWEEN 1 AND 10", name="ck_concern_priority"),
    )
    op.create_index(
        "idx_skin_profile_concerns_profile", "skin_profile_concerns", ["skin_profile_id"]
    )


def downgrade() -> None:
    op.drop_table("skin_profile_concerns")
    op.drop_table("skin_profiles")
    op.drop_table("user_profiles")
    op.drop_table("skin_concerns")
    op.drop_table("skin_types")
