"""ingredients, ingredient_concern_treats, ingredient_skintype_avoid, product_ingredients

Revision ID: ccb49f9b0f47
Revises: 44cfa8e6d5d4
Create Date: 2026-07-09 02:00:00.000000

Hand-written, not autogenerated — no live Postgres was reachable in this session (Docker
wasn't running) to diff against, same constraint the baseline migration hit. Written to
match app/services/ingredients/models.py and ProductIngredient in
app/services/recommendations/models.py, which themselves mirror
database_schemas/skinlytics_postgresql_schema_v3.sql's literal DDL for these four tables.

**Gap closed, milestone-1 audit:** `product_ingredients.product_id` FKs to `products`,
which this migration originally chained directly after the baseline (`50e82a643bf9`) —
before any migration created `products`, so `upgrade()` on a genuinely fresh database
crashed here (`UndefinedTable: relation "products" does not exist`), confirmed live
during the audit. Fixed by splicing `44cfa8e6d5d4` (products/routines/scoring) in between
and repointing this migration's `down_revision` at it instead — `ccb49f9b0f47` had never
actually been executed via `alembic upgrade`/`stamp` on any database (only its DDL was
loaded manually), so repointing it doesn't rewrite any applied history. See
`44cfa8e6d5d4`'s docstring for the full account. The real project database is stamped at
the new head (see PROGRESS.md) rather than upgraded, since these tables already exist
there from the original manual SQL load.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ccb49f9b0f47"
down_revision: str | Sequence[str] | None = "44cfa8e6d5d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "ingredients",
        sa.Column("ingredient_id", sa.Integer(), primary_key=True),
        sa.Column("ingredient_name", sa.String(150), nullable=False, unique=True),
        sa.Column("inci_name", sa.String(150), nullable=True),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()")),
    )

    op.create_table(
        "ingredient_concern_treats",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "ingredient_id",
            sa.Integer(),
            sa.ForeignKey("ingredients.ingredient_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "concern_id",
            sa.Integer(),
            sa.ForeignKey("skin_concerns.concern_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("evidence_strength", sa.String(20), server_default="moderate"),
        sa.CheckConstraint(
            "evidence_strength IN ('weak', 'moderate', 'strong')",
            name="ck_ingredient_concern_evidence",
        ),
        sa.UniqueConstraint("ingredient_id", "concern_id"),
    )

    op.create_table(
        "ingredient_skintype_avoid",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "ingredient_id",
            sa.Integer(),
            sa.ForeignKey("ingredients.ingredient_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "skin_type_id",
            sa.Integer(),
            sa.ForeignKey("skin_types.skin_type_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.UniqueConstraint("ingredient_id", "skin_type_id"),
    )

    op.create_table(
        "product_ingredients",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "product_id",
            sa.Integer(),
            sa.ForeignKey("products.product_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "ingredient_id",
            sa.Integer(),
            sa.ForeignKey("ingredients.ingredient_id"),
            nullable=False,
        ),
        sa.Column("concentration_notes", sa.String(100), nullable=True),
        sa.UniqueConstraint("product_id", "ingredient_id"),
    )


def downgrade() -> None:
    op.drop_table("product_ingredients")
    op.drop_table("ingredient_skintype_avoid")
    op.drop_table("ingredient_concern_treats")
    op.drop_table("ingredients")
