"""ingredients, ingredient_concern_treats, ingredient_skintype_avoid, product_ingredients

Revision ID: ccb49f9b0f47
Revises: 50e82a643bf9
Create Date: 2026-07-09 02:00:00.000000

Hand-written, not autogenerated — no live Postgres was reachable in this session (Docker
wasn't running) to diff against, same constraint the baseline migration hit. Written to
match app/services/ingredients/models.py and ProductIngredient in
app/services/recommendations/models.py, which themselves mirror
database_schemas/skinlytics_postgresql_schema_v3.sql's literal DDL for these four tables.

**Known gap, not introduced here:** `product_ingredients.product_id` FKs to `products`,
but no earlier migration creates `products` — `50e82a643bf9`'s baseline only covers
user_profiles/skin_types/skin_concerns/skin_profiles/skin_profile_concerns. Products,
routines, scores, and now these ingredient tables all exist on the real project database
(loaded directly from the v3 SQL file per PROGRESS.md), but were never individually
migrated — this file's `upgrade()` will fail on a genuinely fresh, empty database until
that gap is closed (PROGRESS.md "Verify alembic upgrade head against a genuinely fresh
database" already tracks this). On the real project database, apply this via
`alembic stamp ccb49f9b0f47`, not `upgrade` — verify with an empty `alembic revision
--autogenerate` diff first, exactly as the baseline migration's docstring describes.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ccb49f9b0f47"
down_revision: str | Sequence[str] | None = "50e82a643bf9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "ingredients",
        sa.Column("ingredient_id", sa.Integer(), primary_key=True),
        sa.Column("ingredient_name", sa.String(150), nullable=False, unique=True),
        sa.Column("inci_name", sa.String(150), nullable=True),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()")),
    )

    op.create_table(
        "ingredient_concern_treats",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "ingredient_id",
            sa.Integer(),
            sa.ForeignKey("ingredients.ingredient_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "concern_id",
            sa.Integer(),
            sa.ForeignKey("skin_concerns.concern_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("evidence_strength", sa.String(20), server_default="moderate"),
        sa.CheckConstraint(
            "evidence_strength IN ('weak', 'moderate', 'strong')",
            name="ck_ingredient_concern_evidence",
        ),
        sa.UniqueConstraint("ingredient_id", "concern_id"),
    )

    op.create_table(
        "ingredient_skintype_avoid",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "ingredient_id",
            sa.Integer(),
            sa.ForeignKey("ingredients.ingredient_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "skin_type_id",
            sa.Integer(),
            sa.ForeignKey("skin_types.skin_type_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.UniqueConstraint("ingredient_id", "skin_type_id"),
    )

    op.create_table(
        "product_ingredients",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "product_id",
            sa.Integer(),
            sa.ForeignKey("products.product_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "ingredient_id",
            sa.Integer(),
            sa.ForeignKey("ingredients.ingredient_id"),
            nullable=False,
        ),
        sa.Column("concentration_notes", sa.String(100), nullable=True),
        sa.UniqueConstraint("product_id", "ingredient_id"),
    )


def downgrade() -> None:
    op.drop_table("product_ingredients")
    op.drop_table("ingredient_skintype_avoid")
    op.drop_table("ingredient_concern_treats")
    op.drop_table("ingredients")
