"""add lifestyle tracking fields

Revision ID: 38428122f610
Revises: 42133e6dde31
Create Date: 2026-07-28 07:00:38.069314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38428122f610'
down_revision: Union[str, Sequence[str], None] = '42133e6dde31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifestyle_logs', sa.Column('alcohol_mls', sa.Float(), nullable=True))
    op.add_column('lifestyle_logs', sa.Column('sun_exposure_minutes', sa.Integer(), nullable=True))
    op.add_column('lifestyle_logs', sa.Column('diet_quality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifestyle_logs', 'diet_quality')
    op.drop_column('lifestyle_logs', 'sun_exposure_minutes')
    op.drop_column('lifestyle_logs', 'alcohol_mls')
    op.create_table('professional_availability',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('professional_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('professional_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('slot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], name=op.f('professional_availability_professional_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('professional_availability_pkey'))
    )
    op.create_index(op.f('ix_professional_availability_slot_date'), 'professional_availability', ['slot_date'], unique=False)
    op.create_index(op.f('ix_professional_availability_professional_id'), 'professional_availability', ['professional_id'], unique=False)
    # ### end Alembic commands ###
