import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import api from "../services/api";

const Value = ({ label, value }) => <p><strong>{label}:</strong> {value || "Not provided"}</p>;

function CaseDetails() {
  const { id } = useParams(); const [data, setData] = useState(null); const [recommendation, setRecommendation] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api.get(`/consultations/case/${id}`).then(({ data: result }) => { setData(result); setRecommendation(result.consultation?.recommendation || ""); }).catch((err) => setError(err.response?.data?.detail || "Unable to load this patient case.")); }, [id]);
  const saveRecommendation = async () => { try { await api.put(`/consultations/recommend/${id}`, { recommendation }); setData((current) => ({ ...current, consultation: { ...current.consultation, recommendation, status: "Completed" } })); } catch (err) { setError(err.response?.data?.detail || "Unable to save recommendation."); } };
  if (error) return <DashboardLayout><div className="alert alert-danger">{error}</div></DashboardLayout>;
  if (!data) return <DashboardLayout><h3>Loading patient case...</h3></DashboardLayout>;
  const latest = data.progress?.at(-1);
  return <DashboardLayout><h2 className="mb-4">Patient Case</h2><div className="card shadow border-0 mb-4"><div className="card-body"><h4>Patient Information</h4><Value label="Name" value={data.user?.name} /><Value label="Email" value={data.user?.email} /></div></div><div className="row"><div className="col-lg-6 mb-4"><section className="card shadow border-0 h-100"><div className="card-body"><h4>Skin Profile</h4><Value label="Age" value={data.skin_profile?.age} /><Value label="Gender" value={data.skin_profile?.gender} /><Value label="Skin type" value={data.skin_profile?.skin_type} /><Value label="Skin concerns" value={data.skin_profile?.skin_concerns} /><Value label="Allergies" value={data.skin_profile?.allergies} /><Value label="Sensitivities" value={data.skin_profile?.sensitivities} /></div></section></div><div className="col-lg-6 mb-4"><section className="card shadow border-0 h-100"><div className="card-body"><h4>Lifestyle</h4><Value label="Sleep duration" value={data.lifestyle?.sleep_duration} /><Value label="Water intake" value={data.lifestyle?.water_intake} /><Value label="Exercise" value={data.lifestyle?.exercise} /><Value label="Stress level" value={data.lifestyle?.stress_level} /><Value label="Environmental exposure" value={data.lifestyle?.environmental_exposure} /></div></section></div></div><section className="card shadow border-0 mb-4"><div className="card-body"><h4>Progress History</h4>{latest && <p className="text-muted">Latest assessment: {latest.assessment_date} · Skin score: {latest.skin_score ?? "Not assessed"} · Hydration: {latest.hydration_score ?? "Not assessed"} · Acne level: {latest.acne_level ?? "Not assessed"}</p>}{data.progress?.length ? <div className="table-responsive"><table className="table align-middle"><thead><tr><th>Date</th><th>Skin score</th><th>Hydration</th><th>Acne level</th><th>Notes</th></tr></thead><tbody>{data.progress.map((item) => <tr key={item.progress_id}><td>{item.assessment_date}</td><td>{item.skin_score ?? "—"}</td><td>{item.hydration_score ?? "—"}</td><td>{item.acne_level ?? "—"}</td><td>{item.notes || "—"}</td></tr>)}</tbody></table></div> : <p className="text-muted mb-0">No progress assessments are available for this patient.</p>}</div></section><section className="card shadow border-0"><div className="card-body"><h4>Professional Recommendation</h4><textarea className="form-control" rows="8" placeholder="Write skincare guidance here..." value={recommendation} onChange={(event) => setRecommendation(event.target.value)} /><button className="btn btn-success mt-3" onClick={saveRecommendation}>Save Recommendation</button></div></section></DashboardLayout>;
}
export default CaseDetails;
