import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import api from "../services/api";

export default function ConsultantCase() {
  const { id } = useParams(); const [data, setData] = useState(null); const [message, setMessage] = useState(""); const [form, setForm] = useState({ recommendation:"", consultant_notes:"", progress_observations:"", routine_suggestions:"", follow_up_suggestion:"", requires_dermatologist:false });
  useEffect(() => { api.get(`/consultations/case/${id}`).then((response) => { setData(response.data); const c=response.data.consultation; setForm((current) => ({...current, recommendation:c.recommendation || "", consultant_notes:c.consultant_notes || "", progress_observations:c.progress_observations || "", routine_suggestions:c.routine_suggestions || "", follow_up_suggestion:c.follow_up_suggestion || "", requires_dermatologist:!!c.requires_dermatologist})); }).catch((err) => setMessage(err.response?.data?.detail || "Unable to load case.")); }, [id]);
  const submit = async (event) => { event.preventDefault(); try { const response=await api.put(`/consultations/${id}/review`, form); setMessage(response.data.message); setData((old) => ({...old, consultation:response.data.consultation})); } catch (err) { const detail = err.response?.data?.detail || err.response?.data?.message || "Unable to save review."; setMessage(`Unable to save review${err.response?.status ? ` (${err.response.status})` : ""}: ${detail}`); } };
  if (!data) return <DashboardLayout><div className="container py-4">{message || "Loading client case..."}</div></DashboardLayout>;
  const p=data.skin_profile || {}; const l=data.lifestyle || {}; const ai=data.ai_assessment;
  return <DashboardLayout><div className="container py-4"><h2>Client Case</h2>{message && <div className="alert alert-info">{message}</div>}<div className="row"><section className="col-lg-6"><div className="card p-3 mb-3"><h4>Skin Profile</h4><p><b>{data.user?.name}</b> · {data.user?.email}</p><p>Skin type: {p.skin_type || "Not provided"}</p><p>Concerns: {p.skin_concerns || "Not provided"}</p><p>Allergies: {p.allergies || "Not provided"}</p></div></section><section className="col-lg-6"><div className="card p-3 mb-3"><h4>Lifestyle</h4><p>Sleep: {l.sleep_duration ?? "Not provided"}</p><p>Water intake: {l.water_intake ?? "Not provided"}</p><p>Exercise: {l.exercise || "Not provided"}</p><p>Stress: {l.stress_level || "Not provided"}</p></div></section></div>{ai && <section className="card p-3 mb-3"><h4>AI Assessment</h4><p>Skin health score: {ai.final_score}/100 · Condition: {ai.condition_score} · Lifestyle: {ai.lifestyle_score} · Sleep: {ai.sleep_score} · Hydration: {ai.hydration_score} · Routine: {ai.routine_score}</p><p>{ai.condition_summary}</p><p className="text-muted mb-0">AI assessment is informational only, not a medical diagnosis.</p></section>}<section className="card p-3 mb-3"><h4>Progress History</h4>{data.progress?.length ? <ul>{data.progress.map((record) => <li key={record.progress_id}>{record.assessment_date}: score {record.skin_score ?? "—"}; {record.notes || "No notes"}</li>)}</ul> : <p>No progress records.</p>}</section><section className="card p-3"><h4>Consultant Review</h4><form onSubmit={submit}>{[["recommendation","General skincare guidance"],["consultant_notes","Review notes"],["progress_observations","Progress observations"],["routine_suggestions","Routine and product suggestions"],["follow_up_suggestion","Follow-up suggestion"]].map(([key,label]) => <div className="mb-3" key={key}><label className="form-label">{label}</label><textarea className="form-control" required={key === "recommendation"} value={form[key]} onChange={(event) => setForm({...form,[key]:event.target.value})} /></div>)}<label className="form-check mb-3"><input className="form-check-input me-2" type="checkbox" checked={form.requires_dermatologist} onChange={(event) => setForm({...form,requires_dermatologist:event.target.checked})} />Recommend dermatologist review</label><button className="btn btn-primary">Save Review</button></form></section></div></DashboardLayout>;
}
