import { useEffect, useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import api from "../services/api";
import "../styles/reports.css";

function Reports() {
  const [reports, setReports] = useState([]); const [selected, setSelected] = useState(null); const [error, setError] = useState("");
  useEffect(() => { api.get("/reports/mine").then(({ data }) => setReports(data)).catch((err) => setError(err.response?.data?.detail || "Unable to load reports.")); }, []);
  const viewReport = async (id) => { try { const { data } = await api.get(`/reports/${id}`); setSelected(data); } catch (err) { setError(err.response?.data?.detail || "Unable to load report."); } };
  const viewPdf = async (id) => { try { const response = await api.get(`/reports/${id}/pdf`, { responseType: "blob" }); const url = URL.createObjectURL(new Blob([response.data], { type: "application/pdf" })); window.open(url, "_blank", "noopener,noreferrer"); setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (err) { setError(err.response?.data?.detail || "Unable to generate PDF."); } };
  return <DashboardLayout><div className="reports-header"><h2>Dermatologist Reports</h2><p>View consultation reports that are available to your account.</p></div>{error && <div className="alert alert-danger">{error}</div>}{!error && !reports.length && <div className="reports-empty">No dermatologist reports are available yet.</div>}<div className="row mt-4">{reports.map((report) => <div className="col-lg-6 mb-4" key={report.report_id}><article className="report-card"><p className="report-date">{report.report_date}</p><h4>Consultation Report</h4><p><strong>Dermatologist:</strong> {report.dermatologist_name || "Not provided"}</p><p>{report.patient_summary || report.clinical_observations || "No summary was provided."}</p><div className="report-actions"><button onClick={() => viewReport(report.report_id)}>View Report</button><button className="report-pdf" onClick={() => viewPdf(report.report_id)}>View PDF</button></div></article></div>)}</div>{selected && <section className="report-detail"><div className="d-flex justify-content-between gap-3"><h3>Report Details</h3><button className="report-close" onClick={() => setSelected(null)}>Close</button></div><p><strong>Dermatologist:</strong> {selected.dermatologist?.name || "Not provided"}</p>{[["Patient Summary", selected.report.patient_summary], ["Clinical Observations", selected.report.clinical_observations], ["Skin Assessment", selected.report.skin_assessment], ["Recommendations", selected.report.recommendations], ["Suggested Skincare Routine", selected.report.skincare_routine], ["Follow-up Instructions", selected.report.follow_up_instructions], ["Additional Notes", selected.report.additional_notes]].map(([label, value]) => value && <div key={label}><h5>{label}</h5><p>{value}</p></div>)}</section>}</DashboardLayout>;
}
export default Reports;
