import { useEffect, useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import api from "../services/api";
import "../styles/skin-assessment.css";

function SkinProfile() {
  const [form, setForm] = useState({ age: "", gender: "", skin_type: "", skin_concerns: "", allergies: "", sensitivities: "" });
  const [image, setImage] = useState(null); const [preview, setPreview] = useState(""); const [profileExists, setProfileExists] = useState(false); const [message, setMessage] = useState(""); const [assessment, setAssessment] = useState(null); const [analyzing, setAnalyzing] = useState(false); const [analysisError, setAnalysisError] = useState("");
  useEffect(() => { Promise.all([api.get("/skin-profile/"), api.get("/skin-assessment/latest")]).then(([profileResponse, assessmentResponse]) => { const data = profileResponse.data; if (data.profile_id) { setProfileExists(true); setForm({ age: data.age || "", gender: data.gender || "", skin_type: data.skin_type || "", skin_concerns: data.skin_concerns || "", allergies: data.allergies || "", sensitivities: data.sensitivities || "" }); if (data.skin_image) setPreview(`http://127.0.0.1:8000/${data.skin_image}`); } if (assessmentResponse.data) setAssessment(assessmentResponse.data); }).catch(() => setMessage("Unable to load your Skin Profile.")); }, []);
  const analyze = async () => { setAnalyzing(true); setAnalysisError(""); try { const { data } = await api.post("/skin-assessment/analyze"); setAssessment(data); return data; } catch (error) { setAnalysisError(error.response?.data?.detail || "AI analysis is temporarily unavailable. Please try again later."); return null; } finally { setAnalyzing(false); } };
  const handleSubmit = async (event) => { event.preventDefault(); setMessage(""); const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value)); if (image) data.append("skin_image", image); try { const response = await api[profileExists ? "put" : "post"]("/skin-profile/", data, { headers: { "Content-Type": "multipart/form-data" } }); setProfileExists(true); setMessage(response.data.message); await analyze(); } catch (error) { setMessage(error.response?.data?.detail || "Unable to save your Skin Profile."); } };
  return <DashboardLayout><div className="container py-4"><div className="card shadow p-4"><h2 className="mb-4">Skin Profile</h2><form onSubmit={handleSubmit}><div className="row"><Field label="Age"><input type="number" className="form-control" value={form.age} onChange={(e) => setForm({ ...form, age: e.target.value })} required /></Field><Field label="Gender"><select className="form-select" value={form.gender} onChange={(e) => setForm({ ...form, gender: e.target.value })} required><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></Field></div><Field label="Skin Type"><select className="form-select" value={form.skin_type} onChange={(e) => setForm({ ...form, skin_type: e.target.value })} required><option value="">Select</option><option>Normal</option><option>Dry</option><option>Oily</option><option>Combination</option><option>Sensitive</option></select></Field><Field label="Skin Concerns"><textarea rows="3" className="form-control" value={form.skin_concerns} onChange={(e) => setForm({ ...form, skin_concerns: e.target.value })} /></Field><Field label="Allergies"><textarea rows="2" className="form-control" value={form.allergies} onChange={(e) => setForm({ ...form, allergies: e.target.value })} /></Field><Field label="Sensitivities"><textarea rows="2" className="form-control" value={form.sensitivities} onChange={(e) => setForm({ ...form, sensitivities: e.target.value })} /></Field><Field label="Upload Skin Image"><input type="file" accept="image/*" className="form-control" onChange={(e) => { const file = e.target.files[0]; setImage(file || null); if (file) setPreview(URL.createObjectURL(file)); }} /></Field>{preview && <div className="text-center mb-4"><img src={preview} alt="Skin preview" className="skin-preview" /></div>}<button className="btn btn-primary">{profileExists ? "Update Skin Profile" : "Save Skin Profile"}</button></form>{message && <div className="alert alert-info mt-4">{message}</div>}{profileExists && <section className="assessment-start"><div><h3>AI Skin Assessment</h3><p>Get general skincare guidance based on your saved profile and available lifestyle information. This is not a medical diagnosis.</p></div><button className="assessment-button" onClick={analyze} disabled={analyzing}>{analyzing ? "Analyzing your skin..." : "Analyze My Skin Profile"}</button></section>}{analysisError && <div className="alert alert-warning mt-4">{analysisError}</div>}{assessment && <AssessmentResult assessment={assessment} />}</div></div></DashboardLayout>;
}
function Field({ label, children }) { return <div className="mb-3 col-12"><label className="form-label">{label}</label>{children}</div>; }
function AssessmentResult({ assessment }) { const breakdown = [["Skin Condition", assessment.condition_score], ["Lifestyle", assessment.lifestyle_score], ["Routine", assessment.routine_score], ["Sleep", assessment.sleep_score], ["Hydration", assessment.hydration_score]]; return <section className="assessment-result"><h3>Skin Health Score</h3><div className="final-score">{assessment.final_score} <span>/ 100</span></div><h4>Score Breakdown</h4><div className="score-grid">{breakdown.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><h3 className="mt-4">AI Skin Assessment</h3><p><strong>Skin Type:</strong> {formSkinType(assessment)}</p><p><strong>Severity:</strong> {assessment.severity}</p><p><strong>Risk Level:</strong> {assessment.risk_level}</p><List title="Primary Concerns" values={assessment.primary_concerns} /><h5>AI Summary</h5><p>{assessment.condition_summary}</p><List title="Observations" values={assessment.observations} /><List title="Recommendations" values={assessment.recommendations} /><List title="Morning Routine" values={assessment.morning_routine} /><List title="Night Routine" values={assessment.night_routine} /><List title="Ingredients to Look For" values={assessment.ingredients_to_look_for} /><List title="Ingredients to Avoid" values={assessment.ingredients_to_avoid} /><p className="assessment-disclaimer">{assessment.disclaimer || "This AI-generated assessment is for informational purposes only and is not a medical diagnosis. Consult a qualified dermatologist for medical concerns."}</p></section>; }
function formSkinType(assessment) { return assessment.skin_type || "Based on your saved Skin Profile"; }
function List({ title, values }) { return <div className="assessment-list"><h5>{title}</h5><ul>{values?.map((value, index) => <li key={`${title}-${index}`}>{value}</li>)}</ul></div>; }
export default SkinProfile;
