"""Curated ingredient knowledge base — Milestone 3, Part 2.

A citable starter set of well-established cosmetic-science facts about common
skincare actives, drawn from standard dermatology references rather than any
single proprietary dataset, so they are safe to ship in the repo.

Each tuple:
  name, scientific_category, description, benefits, side_effects,
  skin_type_compat, concern_compat, comedogenic_rating (0-5), references

The product catalogue (app/product_catalog.py) links to these by name and
auto-derives each product's skin-type / concern compatibility and ingredient
benefits from the entries here, so this file is the single source of truth for
ingredient science across the app.
"""

INGREDIENT_KB: list[tuple] = [
    ("Niacinamide", "Vitamin B3",
     "A water-soluble form of vitamin B3 that supports the skin barrier and regulates sebum.",
     "Reduces excess oil, evens tone, strengthens the barrier, calms redness.",
     "Well tolerated; very high concentrations may cause transient flushing in sensitive users.",
     "oily,combination,normal,sensitive,dry", "oiliness,redness,hyperpigmentation,acne,enlarged pores", 0,
     "Journal of Cosmetic Dermatology; standard INCI monographs"),
    ("Vitamin C", "Antioxidant (L-ascorbic acid)",
     "A potent antioxidant that neutralises free radicals and inhibits melanin production.",
     "Brightens, fades dark spots, boosts collagen, defends against pollution and UV damage.",
     "Unstable in light and air; higher concentrations can sting sensitive skin.",
     "oily,combination,normal,dry", "hyperpigmentation,dark spots,dullness,fine lines", 0,
     "British Journal of Dermatology; Pinnell et al. topical antioxidant studies"),
    ("Vitamin E", "Antioxidant (tocopherol)",
     "A lipid-soluble antioxidant that protects cell membranes and stabilises other actives.",
     "Moisturises, protects the barrier, and works synergistically with vitamin C.",
     "Pure tocopherol is mildly comedogenic for very acne-prone skin.",
     "dry,normal,combination", "dryness,fine lines,dullness", 2,
     "Free Radical Biology & Medicine; cosmetic antioxidant reviews"),
    ("Ferulic Acid", "Antioxidant",
     "A plant-derived antioxidant that stabilises and boosts vitamins C and E.",
     "Extends antioxidant protection and enhances photoprotection.",
     "Rarely irritating; generally very well tolerated.",
     "oily,combination,normal,dry,sensitive", "dullness,fine lines,hyperpigmentation", 0,
     "Journal of Investigative Dermatology, Lin et al."),
    ("Retinol", "Retinoid",
     "A vitamin-A derivative that accelerates cell turnover and stimulates collagen.",
     "Softens wrinkles and fine lines, clears acne, fades pigmentation over time.",
     "Causes purging, dryness and sun sensitivity; avoid in pregnancy.",
     "normal,combination,oily", "wrinkles,fine lines,acne,hyperpigmentation", 1,
     "New England Journal of Medicine retinoid reviews; AAD guidance"),
    ("Retinaldehyde", "Retinoid",
     "A retinoid one step from retinoic acid, more potent than retinol but gentler than tretinoin.",
     "Anti-ageing and anti-acne with a faster onset than retinol.",
     "Can irritate; introduce slowly and always pair with SPF.",
     "normal,combination,oily", "wrinkles,fine lines,acne", 1,
     "British Journal of Dermatology retinaldehyde trials"),
    ("Bakuchiol", "Retinoid alternative",
     "A plant-derived compound that mimics retinol's effects without classic retinoid irritation.",
     "Smooths fine lines and improves firmness; suitable for sensitive and pregnant users.",
     "Very well tolerated; a gentle alternative where retinoids are unsuitable.",
     "sensitive,dry,normal,combination,oily", "fine lines,wrinkles,redness", 1,
     "British Journal of Dermatology, Dhaliwal et al. 2019"),
    ("Salicylic Acid", "Beta hydroxy acid (BHA)",
     "An oil-soluble acid that penetrates pores to dissolve sebum and dead cells.",
     "Unclogs pores, clears blackheads and acne, smooths texture.",
     "Can over-dry; do not layer with strong retinoids when starting out.",
     "oily,combination", "acne,oiliness,blackheads,enlarged pores", 0,
     "Journal of the American Academy of Dermatology BHA reviews"),
    ("Glycolic Acid", "Alpha hydroxy acid (AHA)",
     "The smallest AHA; exfoliates the surface for brighter, smoother skin.",
     "Resurfaces, brightens, softens fine lines and evens tone.",
     "Increases sun sensitivity; start at low strength to avoid stinging.",
     "normal,combination,oily", "dullness,hyperpigmentation,fine lines,texture", 0,
     "Dermatologic Surgery AHA peel studies"),
    ("Lactic Acid", "Alpha hydroxy acid (AHA)",
     "A gentler, larger AHA that also has humectant properties.",
     "Exfoliates while hydrating; brightens without the sting of glycolic acid.",
     "Mild photosensitivity; still requires daily SPF.",
     "dry,normal,combination,sensitive", "dullness,dry skin,hyperpigmentation,texture", 0,
     "Journal of Cosmetic Dermatology lactic acid studies"),
    ("Mandelic Acid", "Alpha hydroxy acid (AHA)",
     "A large-molecule AHA derived from almonds, ideal for sensitive or darker skin.",
     "Gently exfoliates, fades pigmentation, and is low-irritation.",
     "Very mild; slower results than glycolic acid.",
     "sensitive,combination,oily,normal", "hyperpigmentation,acne,dullness", 0,
     "Journal of Clinical & Aesthetic Dermatology mandelic acid reviews"),
    ("Azelaic Acid", "Dicarboxylic acid",
     "A multi-tasking acid that is antibacterial, anti-inflammatory and brightening.",
     "Treats acne, rosacea and post-inflammatory pigmentation gently.",
     "Mild tingling or itching possible in the first weeks.",
     "sensitive,combination,oily,normal,dry", "acne,redness,rosacea,hyperpigmentation", 0,
     "British Journal of Dermatology azelaic acid trials"),
    ("Polyhydroxy Acid", "PHA",
     "A next-generation acid (gluconolactone / lactobionic acid) with large molecules.",
     "Exfoliates very gently while adding hydration; suits sensitive skin.",
     "Minimal irritation; a good entry exfoliant.",
     "sensitive,dry,normal,combination", "dullness,texture,dry skin", 0,
     "Cutis PHA tolerability studies"),
    ("Benzoyl Peroxide", "Antibacterial",
     "An oxidising agent that kills acne-causing bacteria within the pore.",
     "Clears and prevents inflammatory acne and reduces breakouts.",
     "Bleaches fabric; can dry and irritate — buffer with moisturiser.",
     "oily,combination", "acne,oiliness", 0,
     "Cochrane review of benzoyl peroxide for acne"),
    ("Sulfur", "Antimicrobial",
     "A traditional keratolytic and antibacterial mineral used for acne and rosacea.",
     "Absorbs oil, unclogs pores and calms inflammatory bumps.",
     "Can be drying and has a mild odour.",
     "oily,combination", "acne,oiliness,redness", 0,
     "Journal of Drugs in Dermatology sulfur reviews"),
    ("Tea Tree Oil", "Botanical antiseptic",
     "An essential oil with antimicrobial and anti-inflammatory activity.",
     "Spot-treats blemishes and reduces acne-related inflammation.",
     "A common sensitiser; must be diluted and can irritate sensitive skin.",
     "oily,combination", "acne,oiliness", 2,
     "Medical Journal of Australia tea tree acne trial"),
    ("Hyaluronic Acid", "Humectant",
     "A polysaccharide humectant that binds many times its weight in water.",
     "Deeply hydrates, plumps fine lines, improves suppleness.",
     "Can feel drying in very low-humidity climates if not sealed with a moisturiser.",
     "oily,combination,normal,dry,sensitive", "dry skin,fine lines,dehydrated", 0,
     "Dermato-Endocrinology review of topical humectants"),
    ("Glycerin", "Humectant",
     "A small humectant that draws water into the outer skin layers.",
     "Hydrates, softens and supports barrier repair; universally tolerated.",
     "None significant.",
     "oily,combination,normal,dry,sensitive", "dry skin,dehydrated,redness", 0,
     "International Journal of Cosmetic Science humectant reviews"),
    ("Ceramides", "Barrier lipid",
     "Lipids that make up the skin's natural barrier and seal in moisture.",
     "Rebuild a compromised barrier, lock in hydration, calm reactive skin.",
     "None significant; excellent for sensitive and eczema-prone skin.",
     "dry,sensitive,normal,combination", "dry skin,redness,sensitive skin,dehydrated", 0,
     "Journal of the American Academy of Dermatology barrier studies"),
    ("Squalane", "Emollient",
     "A stable, lightweight emollient that mimics the skin's own sebum.",
     "Softens, moisturises, and reinforces the barrier without heaviness.",
     "Non-comedogenic and suitable for nearly all skin types.",
     "oily,combination,normal,dry,sensitive", "dry skin,dehydrated,sensitive skin", 0,
     "Molecules journal review of squalane in cosmetics"),
    ("Panthenol", "Provitamin B5",
     "A humectant and emollient provitamin that soothes and supports healing.",
     "Hydrates, reduces redness and improves barrier recovery.",
     "None significant.",
     "sensitive,dry,normal,combination,oily", "redness,dry skin,sensitive skin", 0,
     "Journal of Dermatological Treatment panthenol studies"),
    ("Colloidal Oatmeal", "Botanical soother",
     "Finely milled oat that forms a protective, anti-inflammatory film.",
     "Calms itch and irritation and supports the barrier.",
     "None significant; FDA-recognised skin protectant.",
     "sensitive,dry,normal", "redness,sensitive skin,dry skin", 0,
     "FDA OTC skin protectant monograph"),
    ("Allantoin", "Soother",
     "A gentle compound that soothes and promotes skin-cell regeneration.",
     "Calms irritation and smooths rough skin.",
     "None significant.",
     "sensitive,dry,normal,combination,oily", "redness,sensitive skin,texture", 0,
     "International Journal of Toxicology allantoin assessment"),
    ("Centella Asiatica", "Botanical (cica)",
     "A herb rich in madecassoside that supports wound healing and calms skin.",
     "Soothes irritation, strengthens the barrier and reduces redness.",
     "None significant; a staple of sensitive-skin care.",
     "sensitive,dry,normal,combination,oily", "redness,sensitive skin,acne", 0,
     "Journal of Ethnopharmacology Centella reviews"),
    ("Madecassoside", "Botanical active",
     "A purified active from Centella asiatica with strong soothing properties.",
     "Reduces redness, supports healing and calms reactive skin.",
     "None significant.",
     "sensitive,dry,normal", "redness,sensitive skin", 0,
     "Experimental Dermatology madecassoside studies"),
    ("Aloe Vera", "Botanical humectant",
     "A plant gel that hydrates and cools irritated or sun-exposed skin.",
     "Soothes, lightly hydrates and calms post-sun redness.",
     "Rare allergy in latex-sensitive individuals.",
     "sensitive,oily,combination,normal", "redness,sensitive skin,dehydrated", 0,
     "Iranian Journal of Medical Sciences aloe reviews"),
    ("Peptides", "Signal peptides",
     "Short amino-acid chains that signal the skin to produce collagen.",
     "Improve firmness and elasticity and soften fine lines.",
     "Well tolerated; results are gradual.",
     "dry,normal,combination,oily,sensitive", "fine lines,wrinkles,loss of firmness", 0,
     "International Journal of Cosmetic Science peptide reviews"),
    ("Copper Peptides", "Signal peptides",
     "Copper-bound peptides that support wound healing and collagen synthesis.",
     "Firm, repair and improve overall skin quality.",
     "Avoid layering directly with strong vitamin C.",
     "dry,normal,combination", "fine lines,wrinkles,loss of firmness", 0,
     "Journal of Cosmetic Dermatology copper peptide studies"),
    ("Alpha Arbutin", "Tyrosinase inhibitor",
     "A stable brightening agent that inhibits melanin formation.",
     "Fades dark spots and evens tone with low irritation.",
     "Very well tolerated.",
     "oily,combination,normal,dry,sensitive", "hyperpigmentation,dark spots,dullness", 0,
     "Journal of Cosmetic Dermatology arbutin reviews"),
    ("Tranexamic Acid", "Brightener",
     "An amino-acid derivative that interrupts pigment transfer.",
     "Fades stubborn melasma and post-inflammatory pigmentation.",
     "Well tolerated topically.",
     "oily,combination,normal,dry,sensitive", "hyperpigmentation,dark spots,melasma", 0,
     "Journal of the American Academy of Dermatology tranexamic acid trials"),
    ("Kojic Acid", "Tyrosinase inhibitor",
     "A fungal-derived acid that inhibits melanin production.",
     "Brightens and targets pigmentation.",
     "Can sensitise; may irritate reactive skin.",
     "oily,combination,normal", "hyperpigmentation,dark spots", 0,
     "Journal of Dermatological Science kojic acid studies"),
    ("Liquorice Root Extract", "Botanical brightener",
     "A soothing botanical that both calms and gently brightens.",
     "Reduces redness and fades pigmentation.",
     "None significant.",
     "sensitive,dry,normal,combination,oily", "redness,hyperpigmentation,dullness", 0,
     "Journal of Cosmetic Dermatology liquorice reviews"),
    ("Zinc PCA", "Sebum regulator",
     "A zinc salt that regulates oil and has mild antibacterial action.",
     "Controls shine, refines pores and supports clearer skin.",
     "None significant.",
     "oily,combination", "oiliness,acne,enlarged pores", 0,
     "International Journal of Cosmetic Science zinc PCA studies"),
    ("Clay (Kaolin)", "Absorbent mineral",
     "A gentle absorbent clay that draws out excess oil and impurities.",
     "Mattifies, decongests pores and refines oily skin.",
     "Can over-dry if left on too long.",
     "oily,combination", "oiliness,acne,enlarged pores", 0,
     "Applied Clay Science cosmetic clay reviews"),
    ("Charcoal", "Absorbent",
     "Activated charcoal that binds oil and surface impurities.",
     "Deep-cleanses and decongests oily, clog-prone skin.",
     "Purely a surface cleanser; can be drying in high amounts.",
     "oily,combination", "oiliness,blackheads,enlarged pores", 0,
     "Cosmetic formulation references on activated charcoal"),
    ("Zinc Oxide", "Mineral UV filter",
     "A broad-spectrum mineral filter that reflects and scatters UV.",
     "Protects against UVA and UVB; calming for sensitive skin.",
     "Can leave a white cast on deeper skin tones.",
     "sensitive,dry,normal,combination,oily", "sun protection,redness,sensitive skin", 1,
     "Photodermatology, Photoimmunology & Photomedicine reviews"),
    ("Titanium Dioxide", "Mineral UV filter",
     "A mineral filter offering broad-spectrum, gentle photoprotection.",
     "Shields sensitive and reactive skin from UV damage.",
     "White cast possible; often blended with zinc oxide.",
     "sensitive,dry,normal,combination", "sun protection,sensitive skin", 1,
     "Journal of the American Academy of Dermatology sunscreen reviews"),
    ("Tinosorb S", "Organic UV filter",
     "A modern broad-spectrum organic filter with high photostability.",
     "Provides strong, cosmetically elegant UVA/UVB protection.",
     "Not available in all regions.",
     "oily,combination,normal,dry", "sun protection", 0,
     "Photochemical & Photobiological Sciences filter reviews"),
    ("Shea Butter", "Occlusive emollient",
     "A rich plant butter that softens and seals in moisture.",
     "Deeply nourishes dry and mature skin.",
     "Too rich for very oily or acne-prone skin.",
     "dry,normal", "dry skin,dehydrated", 2,
     "Journal of Oleo Science shea butter reviews"),
    ("Jojoba Oil", "Emollient",
     "A liquid wax ester that closely resembles human sebum.",
     "Balances and moisturises without heaviness.",
     "Low comedogenicity but patch-test on acne-prone skin.",
     "dry,normal,combination,sensitive", "dry skin,dehydrated", 2,
     "Journal of Cosmetic Science jojoba reviews"),
    ("Rosehip Oil", "Facial oil",
     "A dry oil rich in essential fatty acids and provitamin A.",
     "Improves tone, texture and scarring over time.",
     "Oxidises quickly; can be mildly comedogenic.",
     "dry,normal,combination", "hyperpigmentation,fine lines,dry skin", 2,
     "Clinical, Cosmetic & Investigational Dermatology rosehip studies"),
    ("Snail Mucin", "Repair complex",
     "A secretion rich in glycoproteins and hyaluronic acid.",
     "Hydrates, repairs and supports a smoother texture.",
     "Rare sensitivity; patch-test first.",
     "dry,normal,combination,sensitive", "dehydrated,texture,fine lines", 0,
     "Journal of Cosmetic Dermatology snail secretion reviews"),
    ("Green Tea Extract", "Antioxidant botanical",
     "Polyphenol-rich extract with antioxidant and anti-inflammatory action.",
     "Calms, protects against pollution and helps control oil.",
     "None significant.",
     "oily,combination,normal,sensitive", "oiliness,redness,dullness", 0,
     "Journal of the American Academy of Dermatology green tea reviews"),
    ("Caffeine", "Vasoconstrictor antioxidant",
     "An antioxidant that temporarily tightens and de-puffs skin.",
     "Reduces the look of puffiness and dark under-eye circles.",
     "Temporary, cosmetic effect only.",
     "oily,combination,normal,dry", "puffiness,dark circles,dullness", 0,
     "Journal of Cosmetic Dermatology caffeine eye studies"),
    ("Urea", "Humectant / keratolytic",
     "A dual-action humectant that hydrates at low doses and exfoliates at high doses.",
     "Softens rough, dry and flaky skin.",
     "Higher concentrations can sting broken skin.",
     "dry,normal", "dry skin,texture,dehydrated", 0,
     "Journal of Clinical & Aesthetic Dermatology urea reviews"),
]
