// Report Exporter Utility for HTML/PDF Printing and CSV Export

export function downloadCSV(filename, headers, rows) {
  const csvContent = "data:text/csv;charset=utf-8," 
    + [headers.join(","), ...rows.map(e => e.map(val => `"${String(val).replace(/"/g, '""')}"`).join(","))].join("\n");
  
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function printClinicalReport(title, subtitle, contentHtml) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to export PDF reports.");
    return;
  }

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap');
          body {
            font-family: 'Plus Jakarta Sans', sans-serif;
            margin: 40px;
            color: #0f172a;
            background: #fff;
          }
          .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 2px solid #0284c7;
            padding-bottom: 16px;
            margin-bottom: 24px;
          }
          .brand {
            font-size: 24px;
            font-weight: 800;
            color: #0284c7;
            letter-spacing: -0.03em;
          }
          .tagline {
            font-size: 12px;
            color: #64748b;
            text-transform: uppercase;
            letter-spacing: 0.08em;
          }
          .report-meta {
            text-align: right;
            font-size: 12px;
            color: #475569;
          }
          .section-title {
            font-size: 16px;
            font-weight: 700;
            color: #0369a1;
            margin-top: 24px;
            margin-bottom: 12px;
            border-left: 4px solid #0284c7;
            padding-left: 10px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
            margin-bottom: 20px;
          }
          th, td {
            border: 1px solid #e2e8f0;
            padding: 10px 14px;
            font-size: 13px;
            text-align: left;
          }
          th {
            background-color: #f8fafc;
            font-weight: 600;
            color: #334155;
          }
          .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
          }
          .badge-safe { background: #dcfce7; color: #15803d; }
          .badge-warning { background: #fef3c7; color: #b45309; }
          .badge-danger { background: #fee2e2; color: #b91c1c; }
          .footer {
            margin-top: 40px;
            border-top: 1px solid #e2e8f0;
            padding-top: 16px;
            font-size: 11px;
            color: #94a3b8;
            text-align: center;
          }
          @media print {
            body { margin: 0; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="brand">AI SKIN INTELLIGENCE</div>
            <div class="tagline">Clinical Skincare & Photodermatology Engine</div>
          </div>
          <div class="report-meta">
            <div><strong>${title}</strong></div>
            <div>Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
            <div>Ref: REG-${Math.floor(100000 + Math.random() * 900000)}</div>
          </div>
        </div>
        <p style="font-size: 14px; color: #475569; margin-bottom: 20px;">${subtitle}</p>
        <div>${contentHtml}</div>
        <div class="footer">
          <p>Confidential Medical Skincare Record • Generated by AI Skin Intelligence Platform • Formulated under Clinical Practice Guidelines</p>
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 400);
}
